### ISSUE TITLE
param ID in url call

### ISSUE THREAD

**Issue by Addviso** [mailjet/mailjet-apiv3-php-simple#1]
If you do a function like : 
function getList($listID) {
    $mj = new Mailjet();
    $params = array(
        "method" => "GET",
        "ID" => $listID
    );
    echo "success - create list ".$listID;
    return $mj->contactslist($params);
}

Because you unset ID at line 52, the ID is not present in url params, so you can't retrieve this list (or whatever) by it's ID.

Scott

**Comment by GuillaumeBadi** [comment]
### Hey @Addviso :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
