### ISSUE TITLE
upload CSV with existing email

### ISSUE THREAD

**Issue by wrossier** [mailjet/mailjet-apiv3-php-simple#100]
Hello,

When i upload a CSV file with an existing email in mailjet database, the API don't update the row ?

(https://github.com/mailjet/mailjet-apiv3-php-simple/tree/master/samples)

Thanks for helping
will

**Comment by arnaudbreton** [comment]
Hi @wrossier,

Thanks for reaching out! 
Could you please contact our (support)[https://mailjet.com/support/ticket] with additional information (email to update, hour of your upload, the code executed (if modified from our sample), etc).

Thanks a lot! 

Best,
Arnaud.

**Comment by GuillaumeBadi** [comment]
### Hey @wrossier :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
