### ISSUE TITLE
doublons de bounces par campagne

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#102]
Bonjour

Quand j'utilise la méthode bouncestatistics pour lister les bounces d'une campagne, je remarque que j'ai des doublons sur ContactID et donc le même mail... Par contre je remarque que le StateID est différent. Mais du coup les bounces sont surgonflés par cette méthode !

Je comprend pas bien là...

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi,

Pourriez-vous svp contacter notre [équipe support](https://www.mailjet.com/support/ticket) à propos de votre problème. N'hésitez pas à leur fournir de plus amples informations sur les appels API que vous réalisez de votre côté.

Merci de votre compréhension,
Arnaud.
