### ISSUE TITLE
Pb récupérer les stats d'ouvertures

### ISSUE THREAD

**Issue by anardil** [mailjet/mailjet-apiv3-php-simple#103]
Bonjour,

J'ai un problème pour récupérer les emails qui ont ouvert ma campagne via l'API.
Voici le dump de l'objet Mailjet.

object(Mailjet)#336 (12) {
  ["version"] => string(2) "v3"
  ["secure"] => bool(true)
  ["debug"] => int(0)
  ["apiKey"] => string(32) "xxxxxxxxx"
  ["secretKey"] => string(32) "xxxxxxxxx"
  ["apiUrl"] => string(31) "https://api.mailjet.com/v3/REST"
  ["_method"] => string(15) "openinformation"
  ["_request"] => string(3) "GET"
  ["call_url"] => string(69) "https://api.mailjet.com/v3/REST/openinformation?CampaignID=2147483647"
  ["_request_post"] => bool(false)
  ["_response_code"] => int(200)
  ["_response"] => object(stdClass)#342 (3) {
    ["Count"] => int(0)
    ["Data"] => array(0) {
    }
    ["Total"] => int(0)
  }
}

Cela me retourne rien, alors que sur l'interface Mailjet j'ai bien les statisques.

Pouvez-vous m'aider ?
Merci.

**Comment by Gormador** [comment]
Bonjour @anardil ,

Tout d'abord, merci d'utiliser Mailjet !

Concernant votre problème, pourriez-vous nous fournir la partie de votre code concernée par l'appel à la resource `openinformation` et la gestion de la réponse ?
De même, et afin de faciliter la résolution du problème, pourriez-vous ajouter le code `$mj->debug = 2;` _avant_ l'appel et nous fournir l'output ?

Merci d'avance.

**Comment by anardil** [comment]
Bonjour,

Voici une partie de mon code 

			    	//statistics d'ouverture
			    	$mj->debug = 2;
				    $params = array(
				        "method" 					=> "GET",
				        "CampaignID" 				=> $campaign->campaign_api_id,
				    );
				    
				    $result = $mj->openinformation($params);

Voici la capture d'écran en mode debug=2

![capture d ecran 2015-07-09 a 17 27 03](https://cloud.githubusercontent.com/assets/471437/8599278/ca750d3c-265f-11e5-901e-b52064bed7dd.png)

Pour info, sur autre compte mailjet avec l'API je ne rencontre pas ce soucis.
Merci.

**Comment by Gormador** [comment]
Il n'y a apparemment pas de problème dans votre code. Et, si cela fonctionne avec un autre compte, le souci doit venir des données sur le compte rencontrant l'issue.

Je vous propose donc de contacter [notre support](https://fr.mailjet.com/support/ticket), plus à même de traiter ce genre de problème, et d'y mentionner cette issue github. Cela permettra un meilleur traitement du ticket.

Merci de votre compréhension.
Gaëtan

**Comment by GuillaumeBadi** [comment]
### Hey @anardil :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
