### ISSUE TITLE
HTML not rendered properly in GMail or Yahoo 

### ISSUE THREAD

**Issue by avinash2014** [mailjet/mailjet-apiv3-php-simple#105]
When I am going to send mail on gmail account or yahoo account through mailjet, the message not rendered properly. If it contains BR tag or hyperlink tag it was not rendering properly.
I am new to this library, can anybody know any option set in mail configuration, so HTML contents get rendered properly. 
And one more thing when I am sending mail to Yopmail account, it works fine !!!

**Comment by Gormador** [comment]
Hi @avinash2014,

First of all, thank you for your interest in Mailjet!

Could you provide us with a bit more informations regarding your issue? For example, how are you sending the email (basically the code of your call to the API), the body of your message, ... Basically anything that could help us better locate the origin of the problem.
Don't forget to sanitise what you reply though (no API keys, specific emails, etc...).

Thanks in advance!
Gaëtan
