### ISSUE TITLE
Internal error: List address is automatically generated and can't be changed

### ISSUE THREAD

**Issue by Romano83** [mailjet/mailjet-apiv3-php-simple#107]
Bonjour,

je tombe sur cette erreur lorsque je souhaite envoyer une newsletter à un contact.

Voici le code de la fonction que j'utilise : 
```php
// je récupère au préalable les contacts et je les stocks dans $contacts
$mj = new Mailjet();
$listcontactname = PROJECT . $_SERVER['APPLICATION_ENV'] . date("dmYHis");
// Parameters
$params = array(
		'method' => 'POST',
		'Address' => $contacts,
		'Name' => $listcontactname
);
// Call
$mj->contactslist($params);
```
Et ce que me retourne le débug : 
```
stdClass Object
(
    [ErrorInfo] => 
    [ErrorMessage] => Internal error: List address is automatically generated and can't be changed
    [StatusCode] => 401
)
```

Je tiens à préciser que ce code fonctionnait parfaitement la semaine dernière, lors de différents tests, sur un compte-test que j'avais créé pour tester la nouvelle API.

Depuis, le compte de notre entreprise a migré vers la nouvelle API et le code ne fonctionne plus...
Je n'ai pourtant rien changé au code, j'ai vérifié les clés API et elles sont bonnes.

~~(petite précision, ce code ne fonctionne pas non plus avec la clé API du compte-test...)~~

Merci d'avance pour vos explications.

Romain

*EDIT :* je viens de refaire un test avec la clé API de mon compte-test et tout semble fonctionner. Par contre, toujours cette erreur avec la clé API du compte de l'entreprise.

**Comment by Gormador** [comment]
Bonjour @Romano83,

Tout d'abord, merci de votre intérêt pour Mailjet !

Concernant votre problème, l'action que vous tentez de réaliser a été corrigée dans une version récente de l'API : le retour que vous obtenez est donc normal.

En effet, la propriété `Address` – qui contient l'email pour contacter tous les contacts de la liste – de la resource `contactslist` est, contrairement à ce qu'indique la documentation, read only et l'a toujours été. Vous n'obteniez pas de message d'erreur avant cette nouvelle version de l'API, mais la ligne dans le payload `'Addresse' => $contacts` n'avait pas d'effet en pratique.

Nous avons donc corrigé le comportement de l'API afin de mieux refléter son fonctionnement.
La documentation sera elle aussi corrigée au plus vite.


J'espère que cela répond à votre question.
Gaëtan

**Comment by Romano83** [comment]
D'accord, je comprends mieux l'erreur !

Si je comprends bien ce que vous me dite @Gormador , il n'est plus nécessaire d'inclure cette propriété dans la fonction `contactslist` ?

**Comment by Gormador** [comment]
Il n'a même jamais été nécessaire de le faire et n'avait quoi qu'il arrive aucun effet puisque cette adresse est générée automatiquement.

**Comment by Romano83** [comment]
OK. Il faut dire que la doc de l'API n'était pas très clair à se sujet...

**Comment by Gormador** [comment]
Oui, nous sommes conscients du problème et travaillons à le résoudre dans les meilleurs délais.
