### ISSUE TITLE
Erreur 500 method manyContacts

### ISSUE THREAD

**Issue by Romano83** [mailjet/mailjet-apiv3-php-simple#108]
Bonjour,

je suis une fois de plus confronté à un problème avec l'API.
Lors de l'envoi d'une campagne, je me retrouve avec une erreur de type 500 lorsque j'appelle la méthode `manycontacts`.
Je précise qu'il s'agit d'une campagne avec plus de 30000 contacts pour laquelle j'ajoute les contacts par "paquet" de 5000.

Voici la partie de ma fonction que appelle la méthode `manycontacts`
```php
$arrContacts = explode ( ",", $contacts );
$arrContactsChunck = array_chunk ( $arrContacts, 5000);
foreach ($arrContactsChunck as $arrChunck){
	// Parameters
	$params = array(
			'method' => 'POST',
			'addresses' => $arrChunck,
			'listID' => $list_id
	);
	// Call
	$mj->manyContacts($params);
	$mj->_response_code ? Zend_Registry::get('log')->log('Application_Model_DbTable_Emailing Response 2 = ' . $mj->_response_code, 0) : false;
}
```

Pour info, j'ai lancé une campagne précédente (quelques minutes auparavant) avec environ 10000 contacts qui est passée sans problème (statut de réponse à 201 pour l'ensemble des méthodes de l'API appelées).

Y aurait-il une limitation dans le nombre de contacts qu'on peut ajouter dans une campagne ? Ou le problème vient-il d'ailleurs ?

Merci d'avance pour votre réponse,
Romain

**Comment by arnaudbreton** [comment]
Bonjour @Romano83,

Désolé pour le délai dans notre réponse.
La méthode `manycontacts` est une méthode synchrone qui peut timeout selon le volume de contacts à traiter.
Pour palier à ce problème, nous avons récemment mis en ligne de nouvelles méthodes, asynchrones pour parvenir au même résultat. Vous trouverez les guides relatifs à cela [ici](http://dev.mailjet.com/guides/bulk-guide/).

N'hésitez pas à revenir vers nous si vous avez d'autres questions.
Si votre problème est résolu, merci de bien vouloir fermer cette issue.

Cordialement,
Arnaud.

**Comment by Romano83** [comment]
Bonjout @arnaudbreton.

Effectivement, le problème est résolu. J'avais oublié de fermé l'issue.

Merci encore !

**Comment by GuillaumeBadi** [comment]
### Hey @Romano83 :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
