### ISSUE TITLE
Mail html non interprété avec sendMail

### ISSUE THREAD

**Issue by Thibault-Brocheton** [mailjet/mailjet-apiv3-php-simple#11]
Bonjour,
j'essaye d'envoyer des mails avec la fonction suivante:

function send_mailjet($dest,$subject,$text) {
    $mj = new Mailjet();
    $params = array(
        "method" => "POST",
        "from" => "noreply@mutum.fr",
        "to" => $dest,
        "subject" => $subject,
        "text" => $text
    );
    $result = $mj->sendEmail($params);
    if ($mj->_response_code == 200)
       echo "";
    else
       $error = "Error - ".$mj->_response_code;
    return $result;
  }

Cependant, les balises html ne sont pas interprétées. Y a-t-il des paramètres à ajouter pour interpréter le html ?
ma variable $text commence par:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<_html>
  <_head>
    <*meta content="text/html;charset=utf-8" http-equiv="Content-Type">
ce qui est censé être adapté pour l'affichage du html.

Je viens de voir la page http://dev.mailjet.com/guides/newsletter-guide/ , y a-t-il moyen de faire ce que je recherche sans passer par curl (dont je ne connais pas du tou le fonctionnement ) ?

Merci de votre attention.
Cordialement

**Comment by GuillaumeBadi** [comment]
### Hey @Zangdar1111 :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
