### ISSUE TITLE
Making contact with more than just email

### ISSUE THREAD

**Issue by interneteur** [mailjet/mailjet-apiv3-php-simple#110]
Hi, I was wondering using this 
```
function createContact($Cemail, $country)
{
    $mj = new Mailjet( $apiKey, $secretKey );
    $params = array(
        "method" => "POST",
        "Email" => $Cemail,
    );

    $result = $mj->contact($params);

    if ($mj->_response_code == 201)
       echo "success - created contact ".$Cemail;
    else
       echo "error - ".$mj->_response_code;

    return $result;
}
```

if in this 

```
    $params = array(
        "method" => "POST",
        "Email" => $Cemail,
    );
```

I could add say, first name, last name, country, phone number, etc

**Comment by arnaudbreton** [comment]
Hi @interneteur,

Sorry for the delay in our answer. What you describe can be achieve by creating contact's properties, called `metadata`. You can find the relevant API Guide [here](http://dev.mailjet.com/guides/personalisation-guide/).

Any further questions, don't hesitate. 
If this helped, please close the issue.

Best,
Arnaud.

**Comment by GuillaumeBadi** [comment]
### Hey @nadermx :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
