### ISSUE TITLE
Get newsletters data from Mail-Jet Api

### ISSUE THREAD

**Issue by maaz-rdx** [mailjet/mailjet-apiv3-php-simple#111]
Hi,

I want to get my newsletters from mail-jet and show them in my WordPress page.How can I do this.I new to API and PHP.I have account in mail-jet and have created campaigns and newsletters.Every thing else is set but i have to get newsletters and show them in page(name,thumb,date,description).
Any help will be greatly appreciated?

**Comment by arnaudbreton** [comment]
Hi @maaz-rdx,

Thanks for your interest in Mailjet and our API.
I've noticed that you also open the same question on StackOverflow. I'm closing this one and will follow-up there.

Thanks for your comprehension.
Arnaud.
