### ISSUE TITLE
Relance non ouverts

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#112]
Bonjour à tous !

J'ai une demande d'un client qui n'est pas idiote : il souhaite pouvoir faire une relance sur les non ouverts sur une campagne envoyée. Avez vous prévu ceci dans votre API ?
L'idéal serait de pouvoir créer une liste de contacts depuis un envoi, de ceux n'ayant pas ouvert la news.

Et autre requête : pouvoir dupliquer une campagne (c'était possible sur la V1 mais là je n'ai pas trouvé dans la doc...).

Merci par avance pour vos éclaircissements,

**Comment by eboisgon** [comment]
Bonjour Florianproxi, 

Une méthode disponible pour gérer un campagne de relance est d'utiliser la liste utilisée pour la première campagne et d'utiliser une segmentation pour créer une nouvelle campagne. 

Parmi les fonctionnalités de filtre vous pouvez utilisez la fonction hasopenedsince(X) ou X est un nombre de jour. Cette fonction filtrera les contacts de la liste qui ont ouvert un message depuis X jours. En inversant cette logique, vous obtiendrais donc tous les contacts qui n'ont pas ouvert de messages depuis X jours. 

Si votre dernière campagne a été envoyée, il y a 3 jours vous pouvez créer  un filtre de ce type : 

```
$params_seg = array(
    "method" => "POST",
    "Expression" => "not hasopenedsince(3)",
    "Description" => "not opened for 3 days",
    "Name" => "not opened for 3 days"
);
$result = $mj->contactfilter($params_seg);
if ($mj->_response_code == 201){
   echo "success";
   var_dump($result);
} else {
   echo "error - ".$mj->_response_code;
   var_dump($mj->_response);
}
```

Le petit bémol de cette méthode est que si d'autres messages sont envoyés aux contacts et ouverts dans l’entre-temps, les contacts seront considérés comme ayant ouvert un message. Ce filtre ne discrimine pas par campagne.

Ensuite pour utiliser cet filtre, il ne vous reste plus qu'à spécifier l'identifiant du filtre dans les paramètres de votre newsletter.

```
$params = array(
    "method" => "POST",
    "Locale" => "en_US",
    "Sender" => $sender_name,
    "SenderEmail" => $sender_email,
    "Subject" => $subject,
    "ContactsListID" => $id_list,
    "Title" => $title,
    "SegmentationID" => $id_contactfilter,
);
$result = $mj->newsletter($params);
```

Pour votre seconde question à propos de duplication de campagne, vous trouverez une explication ici pour dupliquer une newsletter. https://github.com/mailjet/mailjet-apiv3-php-simple#duplicating-an-existing-newsletter 

Il vous faudra, en plus de dupliquer la newsletter, copier le contenu de la newsletter.

Le processus complet sera le suivant : 

```
//We want to duplicate the newsletter id #103
//using _DuplicateFrom to specify the ID of the newsletter to duplicate  
$params = array(
	"method" => "POST", 
	"Status" => 0,
	"EditMode" => "html",
	"_DuplicateFrom" => 103	
);

$result = $mj->newsletter($params);
if ($mj->_response_code == 201){
	$id_new_newsletter = $result->Data[0]->ID;
	echo "success: created newsletter\n";
	//finding the content of the newsletter we are duplicating 	
	$params_content = array(
	    "method" => "GET",
	    "Limit" => 100,
	    "ID" => $params["_DuplicateFrom"] 
	);
	$resultContent = $mj->newsletterDetailContent($params_content);
	if ($mj->_response_code == 200){
		//updating the content of the newly created newsletter 
		echo "success: extracted content\n";
	   	$params_new_content = array(
		    "method" => "PUT",
		    "ID" => $id_new_newsletter,
		    "Html-part" => $resultContent->Data[0]->{'Html-part'},
		    "Text-part" => $resultContent->Data[0]->{'Text-part'}
		);
		$resultUpContent = $mj->newsletterDetailContent($params_new_content);
		if ($mj->_response_code == 200){
		   echo "success: copy of content\n";
		   var_dump($resultUpContent);
		} else {
		   echo "error - ".$mj->_response_code;
		   var_dump($mj->_response);
		}
	} else {
	   	echo "error - ".$mj->_response_code;
	   	var_dump($mj->_response);
	}
} else {
   echo "error - ".$mj->_response_code;
   var_dump($mj->_response);
}
```
