### ISSUE TITLE
Tag version v2.0.0-dev not referencing in packagist

### ISSUE THREAD

**Issue by flug** [mailjet/mailjet-apiv3-php-simple#113]

**Comment by arnaudbreton** [comment]
Closing the issue since there is no more description in it. Feel free to open it again or a new one if you need further help. We're always happy to help you!

Cheers,
Arnaud.

**Comment by flug** [comment]
Hi, in packagist.org on this page https://packagist.org/packages/mailjet/mailjet-apiv3-php-simple 
you lib v2.0.0-dev is not referenced. Fix version on you lib !
