### ISSUE TITLE
Avoir distinction soft bounce et hard bounce

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#114]
Bonjour,

Comment avoir la distinction soft bounce et hardbounce via la méthode messagesentstatistics() de l'API ?

Merci de votre aide,

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi, le champ [`StatePermanent`](http://dev.mailjet.com/email-api/v3/messagesentstatistics/) permet de distinguer les deux. Lorsqu'il vaut 1, le message est un hard bounce. 

En espérant avoir répondu à votre question.
Arnaud.

**Comment by florianproxi** [comment]
Merci, mais ce champ reste à 0 chez moi...
Possible de filtrer la méthode messagesentstatistics() sur uniquement les hard bounces ?

**Comment by florianproxi** [comment]
@arnaudbreton merci de répondre rapidement car là ca nous bloque pour un envoi !!!

**Comment by arnaudbreton** [comment]
@florianproxi, pour obtenir une réponse dans les meilleurs délais pour votre problème, je vous invite à contacter directement notre support dédié. Cet espace est principalement réservé aux questions et évolutions de notre wrapper PHP.

Merci de votre compréhension,
Arnaud.

**Comment by arnaudbreton** [comment]
Bonsoir @florianproxi, le problème de signalisation des hard bounces est désormais résolu de notre côté, pour tous les messages envoyés depuis le 1er Octobre.

Pouvez-vous confirmer que cela est désormais résolu de votre côté ?

Merci d'avance.

**Comment by GuillaumeBadi** [comment]
### Hey @florianproxi  :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
