### ISSUE TITLE
Creation d'une Campagne et son Content

### ISSUE THREAD

**Issue by clementinrastavan** [mailjet/mailjet-apiv3-php-simple#115]
Bonjour,

Je voudrais savoir s'il était possible de créer une campagne avec la classe php actuelle.
Je me suis renseigné sur l'APIv3 à ce niveau et j'ai essayé d'en créer une en bidouillant un peu la classe pour m'envoyer vers l'URL https://api.mailjet.com/v3/REST/newsletter quand j'appelle ma fonction de création de campagne (Avec les paramètres correspondant à la doc APIv3).

Hors celà me retourne une erreur 401.
Je ne sais donc pas si je m'y prends mal, ou tout simplement on ne peut pas encore le faire.

Je vous remercie d'avance

**Comment by clementinrastavan** [comment]
Autant pour moi, simple erreur d'inattention

**Comment by GuillaumeBadi** [comment]
### Hey @clementinrastavan :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
