### ISSUE TITLE
Json encode doesnt work with parameters in PHP version 5.3

### ISSUE THREAD

**Issue by giak** [mailjet/mailjet-apiv3-php-simple#118]
this not compatible with PHP version < 5.4.0
json_encode($params, JSON_UNESCAPED_SLASHES)

Need to remove the second parameter to worked in PHP 5.3

We could do this :
        if (version_compare(phpversion(), '5.4.0', '<')) {
            $data= json_encode($params);
        } else {
            $data= json_encode($params, JSON_UNESCAPED_SLASHES);
        }

**Comment by GuillaumeBadi** [comment]
Hi @giak ! 
Sorry for the delay !

I came up with a fix, please let me know if it works for you implementation ! :)
https://travis-ci.org/mailjet/mailjet/mailjet-apiv3-php-simple/builds/85291662

It is already on branch `master`

Best, 
Guillaume

**Comment by giak** [comment]
Hi Guillaume,

i'vent see that https://github.com/mailjet/mailjet-apiv3-php-simple/tree/unescaped_slashes_polyfill
too lazy to read ;)

Thx

PS : good work by the way about your  documention (at least)
http://dev.mailjet.com/guides/

**Comment by arnaudbreton** [comment]
Thanks for your kind words on the new API documentation, glad you love it!
