### ISSUE TITLE
 Tag version v2.0.0-dev not referencing in packagist (reopen)

### ISSUE THREAD

**Issue by flug** [mailjet/mailjet-apiv3-php-simple#121]
Hi, in packagist.org on this page https://packagist.org/packages/mailjet/mailjet-apiv3-php-simple
you lib v2.0.0-dev is not referenced. Fix version on you lib !

**Comment by GuillaumeBadi** [comment]
Hi @flug !

We are currently working on a cleaner and much more maintainable version of the PHP wrapper in another repository, that is planned to be released soon. This v2.0.0-dev tag is not going to be maintained

Best,
Guillaume from Mailjet
