### ISSUE TITLE
Can any one please tell me where i get the $newsletter_id in the function?

### ISSUE THREAD

**Issue by prspace** [mailjet/mailjet-apiv3-php-simple#123]
Can any one please tell me where i get the $newsletter_id in the function? 
showing the documentation https://github.com/mailjet/mailjet-apiv3-php-simple/ 
if you go to the function  getNewsletterDetailcontent($newsletter_id)
I cannot find how to get the newsletter id , as also i have created several newsletter on the main site of the newsletter also.

**Comment by GuillaumeBadi** [comment]
Hey @prspace :airplane: 

When you create a newsletter, you're getting a response with all your nl information, including its ID.

By the way, please be aware that this repository is going to be left as unmaintained. You can use the [new one](https://github.com/mailjet/mailjet-apiv3-php) and get all of your newsletter with:

``` php
$result = $client->get(Resources::$Newsletter);
if ($result->success())
{
 var_dump($result->getData()) // newsletters list
}
```

then you will be able to view the newsletter you would like to get with:

``` php

$mynL = $client->get($Newsletter, ['id' => $newsletter_id])

```

`NewsletterDetailcontent` is used when you want to add a body to a newsletter with either `POST` or `PUT`.

``` php
$body = [
    'Html-part' => "Hello <strong>world</strong>!",
    'Text-part' => "Hello world!"
];
$response = $mj->put(Resources::$NewsletterDetailcontent, ['id' => $id, 'body' => $body]);
```

use `POST`, if you only give a value to `Html-part` or `Text-part`, the other one will be set to empty. use `PUT`, if you only give a value to `Html-part` or `Text-part`, the other one keeps its previous value.

Please let me know if it answers your query :)

Best,
Guillaume

**Comment by GuillaumeBadi** [comment]
Hey ! please let me know if it solved your problem ! :)
