### ISSUE TITLE
Change sender name

### ISSUE THREAD

**Issue by yassersharaf** [mailjet/mailjet-apiv3-php-simple#124]
Hello,
I've been looking for a way to change the sender name but I didn't find in your index. The script works fine but the sender of the massage is always the first name of the email like "info". Is there any way to change the sender name to anything else? 
Thanks

**Comment by GuillaumeBadi** [comment]
Hey @yassersharaf !

Tank you for using Mailjet ! :airplane: 

If you begin with this wrapper, please be aware it won't be actively maintained anymore. We decided to focus on a lighter and cleaner version [here](https://github.com/mailjet/mailjet-apiv3-php) .

With this new Wrapper, sending an email is [easy]()

``` php

<?php
require 'vendor/autoload.php';
use \Mailjet\Resources;

$mj = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'));

$email = [
    'FromEmail' => "pilot@mailjet.com",
    'FromName' => "Mailjet Pilot",
    'Subject' => "Your email flight plan!",
    'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    'Html-part' => "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
    'Recipients' => [[ 'Email' => "passenger@mailjet.com" ]]
];

$response = $mj->post(Resources::$Email, ['body' => $email]);

$response->success() && var_dump($response->getData());
?>

```

Please let me know if you suceeded ! :)

**Comment by yassersharaf** [comment]
Thanks a lot for replying

**Comment by GuillaumeBadi** [comment]
Does it work on your side ? :)

**Comment by yassersharaf** [comment]
include("mailjet/php-mailjet-v3.class.php");
 $mj = new Mailjet( $apiKey, $secretKey );
$to = '{"Email":"'.$user.'"}';
$params = array(
"method" => "POST",
"FromEmail" => "user@domain.com",
"FromName" => "Sender name",
"Subject" => "Subject",
"Html-Part" => "<html></html>",
 "Text-Part" => "text",
"Recipients" => json_decode('['.$to.']',true)
 );                                                       
$result = $mj->send($params);
 if ($mj->_response_code == 200){
echo "success - email sent";
}
 else {
 echo "error - " . $mj->_response_code;                                                 
 }

**Comment by GuillaumeBadi** [comment]
Remember to close the issue unless you have any other question :)
