### ISSUE TITLE
error handling - response reason

### ISSUE THREAD

**Issue by godspeed20** [mailjet/mailjet-apiv3-php-simple#125]
Just wondering if there's a way to get the reason behind a failure? for example I use the following on error:

"Error sending Email ID $key - email attempted was $emailAddress. Error code was " . $mail->_response_code . ", error was " . $mail->_response

When i trap the error (pretty much always a 500), i get no error response. I'm assuming (possibly badly) that the 500 came from the mailjet server not my internal server (as why would my own server respond to its own post query), but I can't see the reason so mailjet aren't able to look into it or help at all. Do you know how i can get the body of the error? The examples only show getting the code but that's not really sufficient unfortunately.

Thanks

**Comment by arnaudbreton** [comment]
Hi @godspeed20, thanks for reaching out to us.

It seems an issue with your account and not really with the simple PHP wrapper as far as I understand. Could you please drop us a line to api@mailjet.com with the code you're running to call the Mailjet API along with the email associated with your Mailjet account, if different from the one you'll write to. This way, we'll be able to understand better what is going wrong for you here.
 
Also, as you can see from the [README](https://github.com/mailjet/mailjet-apiv3-php-simple/blob/master/README.md) this wrapper is now considered as deprecated. We released [a new version](https://github.com/mailjet/mailjet-apiv3-php) aiming to improve the error handling, among other improvements. We encourage you to migrate to this version if you can so you can benefit from the latest updates. We're more than happy to help you migrate your code to this new one.

Sorry for the inconvenience,
Have a good day,
Arnaud.

**Comment by godspeed20** [comment]
Thanks, yeah I figured, was just hoping we'd get a better message so i could pass it to the support guys. it's fine, as you say i need to upgrade to the newer one anyway once the php version is sorted on my end so will do that and then re-review. thanks
