### ISSUE TITLE
testNewsletter error 400 ~  specify a valid and active sender

### ISSUE THREAD

**Issue by YLTP** [mailjet/mailjet-apiv3-php-simple#127]
Bonjour à tous, j'essaye d'envoyer un test de newsletter avec une adresse email qui est pourtant bien active sur mailjet et pourtant j'obtiens toujours cette erreur...
Est ce que quelqu'un a déjà été dans ce cas ? 

Merci d'avance de votre réponse

**Comment by WeshGuillaume** [comment]
Hey :airplane: !

Merci d'utiliser Mailjet!

Peux tu coller ton code ici ? (sans les clefs API et les emails :))

**Comment by YLTP** [comment]
C'est bon je viens de réussir ! Merci quand même de votre réponse rapide !

**Comment by WeshGuillaume** [comment]
:+1:

**Comment by YLTP** [comment]
J'utilisais une valeur pour la propriété sender différente de celle qui était enregistré dans l'interface mailjet pour le contact en question. 

Apparemment dans la v1, il ne comparait pas ces deux valeurs puisque cela fonctionnait alors que les valeurs de sender étaient différentes..

Bonne journée à vous merci encore
