### ISSUE TITLE
Get status by email send id

### ISSUE THREAD

**Issue by parvez-rahaman** [mailjet/mailjet-apiv3-php-simple#128]
```
$mj =new Mailjet( $mjconfig->api_id, $mjconfig->api_secret );

     $subject="Welcome to mysite!";
        $params = array(
        "method" => "POST",
        "from" => "do-not-reply@mysite.com",
        "to" => $to_email,
        "subject" => $subject,
        "html" => $template,
    );

     $result = $mj->sendEmail($params);
```

<br> Result is

```
{#740 ▼
  +"Count": 1
  +"Data": array:1 [▼
    +"ID": 1.9140336662437E+16
  ]
  +"Total": 1
}
```

I just sent a email so i got a result containing an id, and the status of 200, but how can can i know through php api that the email is bounced or blocked? Can you please help me, that would be very helpful. Thank you.

**Comment by WeshGuillaume** [comment]
Hey @prspace !
I guess you are looking for this: 

``` php
<?php
$response = $mj->get(Resources::$Messagesentstatistics, ['id' => $id]);

```

Best,
Guillaume!

**Comment by WeshGuillaume** [comment]
Oups sorry wrong code example (from the new wrapper), but the resource is still the same: 

``` php
$params = array(
    "method" => "VIEW",
    "ID" => $id
);
$result = $mj->messagesentstatistics($params);
```

**Comment by parvez-rahaman** [comment]
Thank you but i'm always getting false in that case.

```
    $result = $mj->sendEmail($params);
    $id = $result->Data[0]->ID; 
    $params = array(
        "method" => "VIEW",
        "ID" => $id
    );
    $result = $mj->messagesentstatistics($params);
```

And my id looks like 1.6888537415439E+16
my call url = "https://api.mailjet.com/v3/REST/messagesentstatistics/1.8295912148639E+16"
and the response is coming as 

```
+"_response": {#740 ▼
    +"ErrorInfo": ""
    +"ErrorMessage": "Unexpected error during GET: Incorrect ID provided - ID type mismatch"
    +"StatusCode": 400
  }
```

**Comment by WeshGuillaume** [comment]
I think your PHP environment is formating your ID, it shoud not look like that indeed. can you try to run this call using curl ?

Something like:

``` cUrl
curl -s \
    -X POST \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
    https://api.mailjet.com/v3/send \
    -H 'Content-Type: application/json' \
    -d '{
        "FromEmail":"pilot@mailjet.com",
        "FromName":"Mailjet Pilot",
        "Subject":"Your email flight plan!",
        "Text-part":"Dear passenger, welcome to Mailjet! May the delivery force be with you!",
        "Html-part":"<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
        "Recipients":[{"Email":"passenger@mailjet.com"}]
    }'
```

**Comment by parvez-rahaman** [comment]
In curl it's ok.
I'm working with laravel 5.1. Now i don't understand what's going on. I know it's out of scope but bo you have any idea how can i get correct ID.

**Comment by WeshGuillaume** [comment]
Can you try with `sprintf('%f', $id)` ?

**Comment by parvez-rahaman** [comment]
I have got the solution! In this library 'mailjet-apiv3-php-simple' inside 'sendRequest' method i just removed the json_encode from this line 

```
    $this->_response = json_decode($buffer, false, 512);
```

and it works perfectly.

**Comment by WeshGuillaume** [comment]
Nice! glad you found it!

**Comment by parvez-rahaman** [comment]
Your suggestion works also. Just adding .0000.Thank you for your support.
