### ISSUE TITLE
ERREUR 500 en ligne | en local ça fonctione ... ERROR 500 online | in local, it's working

### ISSUE THREAD

**Issue by jasinskimathieu** [mailjet/mailjet-apiv3-php-simple#129]
Bonjour à tous, 

Je tente l'envoi d'un email en local et ça fonctionne (après ajout du fichier cacert.pem et édition du fichier php.ini)
Ceci dit, lorsque je tente l'opération en ligne j'ai directement une erreur 500. 

Pourriez-vous me dire d'où provient le problème ? 
## Merci d'avance

Hello world ! 

I try to send an email in local et it's working (with adding of cacert.pem file and edit php.ini). But when I try to execute my script online, I have an error 500.

Could you try to help me ? 

Thank you !

**Comment by WeshGuillaume** [comment]
Hey! Have you got the piece of code that triggers the issue ? I'll try to reproduce it on my side 

Guillaume.

**Comment by jasinskimathieu** [comment]
there are the code  : 

`````` php
<?php
require 'vendor/autoload.php';
use \Mailjet\Resources;

// getenv will allow us to get the MJ_APIKEY_PUBLIC/PRIVATE variables we created before
$apikey = getenv('_');
$apisecret = getenv('_');


$mj = new \Mailjet\Client('_', '_');


$body = [
    'FromEmail' => "info@aftt.be",
    'FromName' => "Mailjet Pilot",
    'Subject' => "Your email flight plan!",
    'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    'Html-part' => "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
    'Recipients' => [
        [
            'Email' => "mathieu.jasinski@aftt.be"
        ]
    ]
];
$response = $mj->post(Resources::$Email, ['body' => $body]);
$response->success() && var_dump($response->getData());

var_dump($response);

?>```
``````

**Comment by WeshGuillaume** [comment]
The code looks okay to me actually. I guess it is more likely to be a server configuration issue. Can you make sure the outgoing requests are allowed in your configurations ?

**Comment by WeshGuillaume** [comment]
I am closing it as it doesn't look like a Wrapper issue but a configuration issue. Feel free to reopen it on the [right repository](https://github.com/mailjet/mailjet-apiv3-php) if you need any help
