### ISSUE TITLE
Add params template to mailjet-apiv3-php-simple

### ISSUE THREAD

**Issue by lynxfg** [mailjet/mailjet-apiv3-php-simple#130]
Hello everybody,

 how can i add a template paramaters to my fonction sendEmail?

Thanks,

**Comment by Zhivko-Mailjet** [comment]
Hi @lynxfg 

Template parameters can not be added in the function "sendEmail". However, you can add template parameters using the function "send". Please note that it requires JSON payload. See here:
https://github.com/mailjet/mailjet-apiv3-php-simple/blob/master/doc/_send-api.md#sending-a-basic-email

Also, please note that the wrapper you use [mailjet-apiv3-php-simple](https://github.com/mailjet/mailjet-apiv3-php-simple) is considered deprecated and is on maintenance only. We strongly advise you to consider implementing our [new PHP wrapper](https://github.com/mailjet/mailjet-apiv3-php).
