### ISSUE TITLE
Set template ID in campaign

### ISSUE THREAD

**Issue by StefanijaK** [mailjet/mailjet-apiv3-php-simple#133]
I have already created a campaign template and I want to use it in the send campaign api. What I can't figure out is where am I supposed to set the template ID. I already tried to do it in when I created the campaign draft, and also in setting the draft content (only html-part and text-part available as parameters) but no use. What am I doing wrong? 
Thanks in advance :)

**Comment by SwithFr** [comment]
Same issue ... ;)

**Comment by latanasov** [comment]
Hi @SwithFr  it is only possible to send the template through the [Send API](https://dev.mailjet.com/guides/#use-the-template-in-send-api) (transactional emails).  If you want to re-use it for Campaigns you can manually get the [template content](https://dev.mailjet.com/email-api/v3/template-detailcontent/) and put it as a [campaigndraft content ](https://dev.mailjet.com/email-api/v3/campaigndraft-detailcontent/) . Keep in mind template language is only supported for transactional emails.

**Comment by SwithFr** [comment]
Okay ! Thanks you ! ;)
