### ISSUE TITLE
Supprimer un contact d'une liste

### ISSUE THREAD

**Issue by RiderFx3** [mailjet/mailjet-apiv3-php-simple#134]
Ticket support n°740212

Bonjour,

J'ai beaucoup de mal à utiliser votre API PHP.
Actuellement j'utilise uniquement la classe php mailjet.

Tous vos exemples PHP utilisent le dossier \ressources\ et les méthodes pour utiliser la classe ne sont jamais expliquées.

J'arrive à vérifier si un utilisateur est présent dans une liste via son email et récupérer son ID, et si il est présent, j'aimerai pouvoir le supprimer de cette liste.

Pour l'instant j'en suis là : 

$mj = new Mailjet();
        $params = array(
            'method' => 'POST',
            'Action' => 'remove',
            'ContactID' => $id,
            'ListID' => $list_to_delete
        );
        $result = $mj->ContactslistManagecontact( $params );
        var_dump($result);

Mais ça me retourne false parce que je dois pas appeler la bonne méthode de classe.

D'autre part, si je veux ensuite rechercher ce contact et qu'il n'est dans aucune liste, je dois simplement refaire une recherche sans préciser le numéro de la liste ?

Merci pour votre aide.

**Comment by latanasov** [comment]
Ticket opened on Mailjet support.
