### ISSUE TITLE
Newsletter : Batchjob ne fonctionne pas

### ISSUE THREAD

**Issue by anardil** [mailjet/mailjet-apiv3-php-simple#15]
Bonjour,

J'ai essayé d'envoyer ma newsletter directement en CURL. Mais apparemment je ne reçois pas la newsletter.

Voici mon test :
curl -X POST --user "xxxxxx:xxxxxxx" https://api.mailjet.com/v3/REST/batchjob -H "Content-Type: application/json" -d '{"RefID":"11", "JobType":"Send newsletter", "Status": "upload"}'

L'API retourne :
{ "Count" : 1, "Data" : [{ "AliveAt" : 0, "APIKeyID" : 185585, "Blocksize" : 0, "Count" : 0, "Current" : 0, "Errcount" : 0, "ErrTreshold" : 0, "ID" : 237404, "JobEnd" : 0, "JobStart" : 0, "JobType" : "Send newsletter", "Method" : "Unknown", "RefId" : 11, "RequestAt" : 0, "Status" : "Upload", "Throttle" : 0 }], "Total" : 1 }

Lorsque je retourne sur l'interface web, dans la liste des campagnes, je ne vois plus apparaitre la newsletter, elle a disparue. Et je n'ai pas reçu dans ma boite email la newsletter.

Avez-vous une idée du problème ?
Merci pour votre aide.

**Comment by gorgorbhey** [comment]
Hello,
i m currently trying to schedule a contact list csv import. But it does not work. here's my code:

    public function sceduleImportContact($id_list, $id_fileuploaded,$id_apikey)
    {
        global $mj;
        $params = array( 
            "method" => "POST ", 
            "JobType" => "Contact list import csv",
            "DataID" => $id_fileuploaded,
            "Status" => "Upload",
            "Method" => "addnoforce", 
            "RefId" => $id_list,
            "ErrTreshold" => "9",
            "APIKeyID" => $id_apikey,
        );
        $buffer= $mj->batchjob ($params);
        return $buffer;
    }

An idea ?

**Comment by arnaudbreton** [comment]
Hey @gorgorbhey, since it's not directly related to the issue of this ticket, could you please create a new one? Thanks a lot!

**Comment by gorgorbhey** [comment]
https://github.com/mailjet/mailjet-apiv3-php-simple/issues/51
;)
