### ISSUE TITLE
Composer/Packagist, anyone ?

### ISSUE THREAD

**Issue by ronanguilloux** [mailjet/mailjet-apiv3-php-simple#17]
Hello Mailjet guys !

It is now two years since [Composer](https://getcomposer.org) & [Packagist](https://packagist.org/)  became the _de facto_ dependency manager & library packager. It dramatically eases the inclusion of an API library in PHP, using [PSR-\* conventions](http://www.php-fig.org) which is another _de facto_ standard of requirements that must be adhered to for autoloader interoperability. Also, [Semantic versioning](http://semver.org/) simplifies a lot this dependency management, with clear `major.minor.bugfix` naming conventions that everyone now uses in the PHP community.

Could you please add a composer file & use semver principes for your library ?

Mailjet is a great localized alternative to other big, english-speaking only emailing providers. I use it with pleasure & confidence. A great clean PHP API would be a new good point for Mailjet !

Thanks in advance !
Ronan

**Comment by GuillaumeBadi** [comment]
### Hey @ronanguilloux :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!

**Comment by ronanguilloux** [comment]
Great jobs, thanks a lot !
