### ISSUE TITLE
VIEW filter

### ISSUE THREAD

**Issue by TheExcalibur** [mailjet/mailjet-apiv3-php-simple#18]
Hi !
Since the "VIEW filter" update, the request to find a contact using his email no longer works.
I was used to do this :
$params = array(
    'method' => 'VIEW',
    'unique' => 'contact@email.com',
);
$result =$mj->contact($params);
But now, it returns the whole contact list...

**Comment by GuillaumeBadi** [comment]
### Hey @TheExcalibur :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!

**Comment by TheExcalibur** [comment]
Thank's for the update ;-)
