### ISSUE TITLE
Unsubscribe a contact from a list

### ISSUE THREAD

**Issue by sebdelprat** [mailjet/mailjet-apiv3-php-simple#19]
Hello,

This function doesn't work :

``` php
function unsubscribeContact($contactID,$listID) {
     $mj = new Mailjet();
     $params = array(
         "method" => "PUT",
         "ListID" => $listID,
         "ID" => $contactID,
         "IsUnsubscribed" => TRUE,
     );

 // Traitement
 }
```

[ErrorMessage] => Object not found
[StatusCode] => 404
Post Arguments
ListID = 2
ID = 2
IsUnsubscribed = 1
Call url https://api.mailjet.com/v3/REST/listrecipient/2 

Why ? Thank you for your help.

**Comment by GuillaumeBadi** [comment]
### Hey @sebdelprat :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
