### ISSUE TITLE
Can't add a contact to a list

### ISSUE THREAD

**Issue by Colir** [mailjet/mailjet-apiv3-php-simple#2]
Hi,
i try to add a contact to a list but without succes

here is my code

```
$params = array(
                'method'    => 'POST',
                'Email' =>  htmlentities($_POST['inputMail'])
            );      
            $result = $mj->contact($params);

            if(isset($result->StatusCode) && $result->StatusCode == '400')
                return false;


            $contact_id = $result->Data[0]->ID;

            // Add the contact to a contact list
            $params = array(
                'method'    => 'POST',
                'ContactID' => $contact_id,
                'ListID'    => $list_id
            );      
            $result = $mj->listrecipient($params);  
```

The problem is that on the first call, mailjet tell me that a contact with this email already exist.

So i can't assign him to a list
I can't retrieve this contact ID

thanks for you help

**Comment by GuillaumeBadi** [comment]
### Hey @Colir :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
