### ISSUE TITLE
[[PERMALINK]] not interpreted

### ISSUE THREAD

**Issue by anardil** [mailjet/mailjet-apiv3-php-simple#20]
Hello,

New problem :).
So now I can send my newsletter. But the permalink is not interpreted => [[PERMALINK]].
When I look the email that I received I can see <a href="[[PERMALINK]]" .....

Could you help me please ?
Thanks you.

Regards.

**Comment by fturk** [comment]
Bonjour, [[PERMALINK]] ne marche pas non plus :D

**Comment by florianproxi** [comment]
Idem pour moi... alors que ca fonctionnait bien la semaine dernière.

**Comment by florianproxi** [comment]
@arnaudbreton @fturk Toujours le même soucis, dérangeant car j'ai deux newsletter à faire partie avant ce soir....

**Comment by arnaudbreton** [comment]
@florianproxi Désolé du retour tardif, pour votre demande précise, pouvez-vous svp contacter directement notre support? Merci !

https://www.mailjet.com/support/ticket

**Comment by florianproxi** [comment]
Arnaud, ticket ouvert à l'instant.

**Comment by arnaudbreton** [comment]
Merci de ta patience @florianproxi. Je te propose de continuer cette discussion sur ce canal.

**Comment by florianproxi** [comment]
@arnaudbreton toujours non fonctionnel..... Ca devient critique là !!!!! Merci

**Comment by arnaudbreton** [comment]
@florianproxi, peux-tu stp nous contacter sur api@mailjet.com stp ? Merci

**Comment by florianproxi** [comment]
@arnaudbreton Voilà qui est fait ;) Merci.

**Comment by psolbach** [comment]
What's the current situation on this? Permalinks are pointing at random french campaigns from 2011, we're close to using Mailjet in production but this is kind of a dealbreaker.

**Comment by psolbach** [comment]
BTW my Support Ticket w/ is open for quite a while now => #300147

**Comment by florianproxi** [comment]
[[PERMALINK]] me donne maintenant un URL beaucoup plus long et qui semble correct, mais pointe vers une page blanche.... Mailjet est en BETA ou quoi ?

**Comment by arnaudbreton** [comment]
Bonjour, 

La correction a été réalisée de notre côté et va être déployée très prochainement. Je ne manquerai pas de revenir vers vous lorsque cela sera le cas.

Merci de votre patience et compréhension.
Arnaud.

**Comment by florianproxi** [comment]
Bonjour Arnaud,

 

Prochainement c’est quand pour toi ? Sur le support on m’avait dit que le déploiement se ferait le lundi 16 mars…. Capture d’écran à l’appui ci-dessous…

 



 

Cordialement,

Florian

 

PROXIMITÉ CLIENT

OBSERVER - ANALYSER  - COMPRENDRE

POUR AGIR EN FIDELISATION ET RENTABILITE

Tél : 02 23 30 03 26 . Fax : 02 23 30 01 80

Email :  <mailto:florian@proximite-client.fr> florian@proximite-client.fr

Web :  <http://www.proximite-client.fr/> proximite-client.fr

 

De : Arnaud BRETON [mailto:notifications@github.com] 
Envoyé : vendredi 24 avril 2015 19:55
À : mailjet/mailjet-apiv3-php-simple
Cc : florianproxi
Objet : Re: [mailjet-apiv3-php-simple] [[PERMALINK]] not interpreted (#20)

 

Bonjour, 

La correction a été réalisée de notre côté et va être déployée très prochainement. Je ne manquerai pas de revenir vers vous lorsque cela sera le cas.

Merci de votre patience et compréhension.
Arnaud.

**Comment by florianproxi** [comment]
@arnaudbreton Arnaud pourrais tu me répondre ?

**Comment by anardil** [comment]
Bonjour,

J'ai refais un test.
[[PERMALINK]] est bien interprété dans l'email mais juste une remarque lorsque l'on arrive sur la page web le lien [[PERMALINK]] n'est plus interprété.

Merci.

**Comment by florianproxi** [comment]
Bonne nouvelle : sur la page miroire via [[PERMALINK]] les variables de personnalisation sont maintenant conservées !

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi,

Vous m'avez devancé ! La correction de ce problème est effectivement en ligne depuis quelques jours désormais, j'attendais de confirmer que tout allait bien pour vous en informer.

N'hésitez pas à ouvrir une autre issue ou à contacter notre support si un problème survenait. 

Merci de votre patience.
Cordialement,
Arnaud.

**Comment by florianproxi** [comment]
Bonjour Arnaud,

Pas de soucis.
J’ai également une soumission de nouveau wrapper (je sais pas faire de fork…).

Je t’ai mis en pièce jointe mon wrapper, c’est surtout l’ajout de nouvelles prises en compte de commandes dans le requestUrlBuilder()  (ligne 279 -> 290) :

else if ($resource == "downloadListeContacts")
                        {
                                $this->call_url = "https://api.mailjet.com/v3/DATA/BatchJob/".$params['jobID']."/CSVData/text:csv";
                               }else if($resource == "downloadErrorImport"){
                            $this->call_url = "https://api.mailjet.com/v3/DATA/BatchJob/".$params['jobID']."/CSVError/text:csv";
                        }else if($resource == "BatchJob"){
                            if(isset($params['Format'])){
                                $this->call_url = "https://api.mailjet.com/v3/DATA/BatchJob/".$params['jobID']."/ExportOptions/application:json";
                            }else{
                                $this->call_url = "https://api.mailjet.com/v3/DATA/BatchJob/".$params['ID']."/CSVData/text:csv";
                            }
                        }

Florian

PROXIMITÉ CLIENT
OBSERVER - ANALYSER  - COMPRENDRE
POUR AGIR EN FIDELISATION ET RENTABILITE
Tél : 02 23 30 03 26 . Fax : 02 23 30 01 80
Email : florian@proximite-client.fr<mailto:florian@proximite-client.fr>
Web : proximite-client.fr<http://www.proximite-client.fr/>

De : Arnaud BRETON [mailto:notifications@github.com]
Envoyé : jeudi 27 août 2015 14:23
À : mailjet/mailjet-apiv3-php-simple <mailjet-apiv3-php-simple@noreply.github.com>
Cc : Florian - Proximité Client <florian@proximite-client.fr>
Objet : Re: [mailjet-apiv3-php-simple] [[PERMALINK]] not interpreted (#20)


Bonjour @florianproxi<https://github.com/florianproxi>,

Vous m'avez devancé ! La correction de ce problème est effectivement en ligne depuis quelques jours désormais, j'attendais de confirmer que tout allait bien pour vous en informer.

N'hésitez pas à ouvrir une autre issue ou à contacter notre support si un problème survenait.

Merci de votre patience.
Cordialement,
Arnaud.

**Comment by arnaudbreton** [comment]
Merci @florianproxi, merci de votre contribution ! @GuillaumeBadi regarde pour l'intégrer à une prochaine release de notre wrapper. 

Nous allons faire en sorte de rendre l'accès à l'API DATA de Mailjet plus générique plutôt que d'ajouter des cas spécifiques pour chaque nouvelle ressource. Nous vous tiendrons bien sûr informé à la release de cette version.

Arnaud.

**Comment by totocrenn** [comment]
Bonjour, je déterre ce sujet car je suis face au même bug, ma variable **[[PERMALINK]]** n'est pas traduite lorsque j'envoie un mail de test pour mon modèle. 
Il semble que le permalink n'est pas le seul, en effet tous les liens de partage ([[SHARE_...]] ne fonctionnent pas non plus. 
Par contre **UNSUB_LINK_FR** et **EMAIL_TO** fonctionnent.
