### ISSUE TITLE
Problem when I try to add sender email that has been deleted before

### ISSUE THREAD

**Issue by anardil** [mailjet/mailjet-apiv3-php-simple#30]
Hello,

I ty to add a sender email that has been deleted before. But when I do that the API returns an error:

  ["_response_code"] => int(400)
  ["_response"] => object(stdClass)#468 (3) {
    ["ErrorInfo"] => string(0) ""
    ["ErrorMessage"] => string(80) "MJ18 A Sender resource with value "xxxx@xxx.xx" for Email already exists."
    ["StatusCode"] => int(400)
  }

But the email has been deleted and in the web interface this email is not listed.

Could you help me ?
Thanks.

**Comment by arnaudbreton** [comment]
Hi @anardil @dapickboy,

This issue is now solved on our side.
Could you please confirm if it's working on your side?

Thanks for your patience,
Arnaud.
