### ISSUE TITLE
CampaignStatistics  are wrong using email as customValue

### ISSUE THREAD

**Issue by AkobmanD** [mailjet/mailjet-apiv3-php-simple#31]
Reading the v3 maijet API reference for the campaginstatistics method, it seems that properties marked as unique can be used to fetch campaignstatistics. 

http://dev.mailjet.com/email-api/v3/campaignstatistics/

Apparently, an email is a contact unique property : 
http://dev.mailjet.com/email-api/v3/contact/

When I use an email as a customValue : 

$customvalue = "test@mydomain.net";
        $params = array(
                "method" => "VIEW",
                "unique" => $customvalue
        );
$this -> m_oMailJet -> campaignstatistics($params);

I get : 

404
Status  
stdClass Object
(
    [ErrorInfo] => 
    [ErrorMessage] => Object not found
    [StatusCode] => 404
)

**Comment by GuillaumeBadi** [comment]
### Hey @AkobmanD :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
