### ISSUE TITLE
How to delete a scheduled campaign ? 

### ISSUE THREAD

**Issue by anardil** [mailjet/mailjet-apiv3-php-simple#32]
Hello,

I created a scheduled campaign via the API  but I want to delete this campaign.
How can I do delete a scheduled campaign ?

Could you help me ?
Thank you.

Kind regards.

**Comment by swooop** [comment]
For your information, we have some new API features for managing your newsletters that you might find useful and there's a blog post here: 
https://www.mailjet.com/blog/introducing-new-newsletter-action-endpoints-api/

and the documentation is here:
http://dev.mailjet.com/guides/newsletter-guide/
