### ISSUE TITLE
Accès à tous les contacts désinscrits d'un compte MailJet (pas d'une Newsletter particulière)

### ISSUE THREAD

**Issue by dgrigy** [mailjet/mailjet-apiv3-php-simple#34]
Hello!

J'ai une question, je souhaites (avant d'envoyer une nouvelle newsletter) récupérer la liste de tous les contacts qui se sont désinscrits (toutes newsletter confondus).

J'ai trouvé une méthode qui me paraissait intéressante, mais elle ne me retourne pas les désinscrits... (il y en a bien 1 j'ai vérifié dans l'interface web de mailjet) :
$params = array(
'IsUnsubscribed' => true
);
$response = $mailJetObject->contact($params);

Si je retire le param IsUnsubscribed la fonction me retourne bien tous mes contacts, mais les valeurs de [UnsubscribedAt] et [UnsubscribedBy] rentent vident...

Quelqu'un a-t-il une idée?

Merci!

**Comment by CharlesCollas** [comment]
Bonjour @dgrigy ,

Est-ce que la réponse précédente vous a permis de solutionner votre problème ?

Merci

**Comment by dgrigy** [comment]
Hello,

En effet je viens seulement de tester et cela répond à ma question (quoique je trouve le principe plus long qu'auparavant surtout qu'il y a un paramètre IsUnsubscribed dans la méthode contact). 

Voici la solution pour récupérer un tableau avec la liste des adresses mails désinscrites : 

$arrayIDContactUnsub = array();
$arrayContactUnsub = array();

$params = array(
   'Unsub' => true
);
$responseIDUnsub = $mailJetObject->listrecipient($params);

if(!empty($responseIDUnsub->Data))
{
	foreach($responseIDUnsub->Data AS $objContactUnsub)
	{	
		$arrayIDContactUnsub[] = $objContactUnsub->ContactID;
	}
}


$params = array();
$responseContact = $mailJetObject->contact($params);
if(!empty($responseContact->Data))
{
	foreach($responseContact->Data AS $objContact)
	{
		if(in_array($objContact->ID, $arrayIDContactUnsub))
		{
			$arrayContactUnsub[] = $objContact->Email;
		}
	}
}


Merci à tous pour votre aide!
