### ISSUE TITLE
response_code 404 while executing updateContactData

### ISSUE THREAD

**Issue by JokePortegies** [mailjet/mailjet-apiv3-php-simple#35]
I found your mailjet-apiv3-php-simple-library and it seems to be exactly what I'm looking for, because I want to extend the formdata, in the widget of the original plugin for Wordpress: I want to register nog only the emailaddress, but also a name or the name of an organisation.

I thought the function updateContactData() would help me with that. I managed to register the contact bij using the addContact-method of the original plugin for Wordpress, I have captured the contact_id and I use this contact_id as a parameter for updateContactData(). 

The response-code I get is a 404. I think that means that I'm doing a call to a non-existing method. What could be wrong?

**Comment by CharlesCollas** [comment]
Hello,

I guess the problem comes from your ```getContact``` function.
In this wrapper, when you need to get a unique result, you need to use ```VIEW``` instead of ```GET``` and to provide an ```ID``` or ```unique``` field.
In that case, because you want to retrieve the ```ID```, you'll need to provide the ```unique``` field, which for a contact is its ```email``` (see http://dev.mailjet.com/email-api/v3/contact/).

This gives the following function:

```php
function getContact($email) {
	$mj = new Mailjet('', '');
	$params = array(
		"method" => "VIEW",
		"unique" => $email
	);

	$mj->contact($params);

	return $mj->_response->Data[0]->ID;
}
```

Please let me know if it works once you've integrated it in your workflow.

**Comment by JokePortegies** [comment]
Thanks so much for your patience to keep looking with me. Wishing you all the best for 2015!

My testroutine has become this: I have register the same emailadres over and over again. Every time it is registered, I delete it from the list. 

With this new getContact-function - with the email-adress as unique identifier - I get the same contact-ID over and over again. So I conclude deleting is nog deleting, but keeping a contact in some sort of trash, keeping its ID save. 
With the old getContact-function - with the list-ID, the Email-adress and the GET - I get an incrementing ID, a new one for every time I register the email-adress. 
But the ID I àm getting - with the new function ànd with the old function - still gives me the 10 deleted contacts from the getContactData-function and the 404-error in the updateContactData. 

I'm thinking: could I use the email as identifier for the updateContactData too? I tried it, but making this $params-array still gives the 404:    
 $params = array(
        'Email' => $email,
        'Data' => $data,
        'method' => 'PUT'
    );

**Comment by CharlesCollas** [comment]
Hey,

Sorry for the late answer.
Thanks, all the best for 2015 too :)

Yes you can use the email as identifier for the updateContactData too, this way:

```php

function updateContactData($email) {
	$mj = new Mailjet('', '');

	$data = array(array('Name' => 'lastname', 'Value' => 'Jet'), array('Name' => 'firstname', 'Value' => 'Mail'));

	$params = array(
		'unique' => $email,
		'Data' => $data,
		'method' => 'PUT'
	);

	$result = $mj->contactdata($params);

	if ($mj->_response_code == 200)
       echo "success - data changed";
    else
       echo "error - ".$mj->_response_code;

	return $result;
}

```

Just replace the ```data``` array with your data and call this function with an email as a string.

Please let me know if it's fine from your side.

**Comment by JokePortegies** [comment]
YES!!!! Finally! Thank you so much! The "unique"-keyword did the trick! 
Thanks again!

**Comment by tfoucault** [comment]
Thanks you a lot for this tip ! With the unique key instead of ContactID it works perfectly.

**Comment by GuillaumeBadi** [comment]
### Hey @JokePortegies :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
