### ISSUE TITLE
newsletterDetailContent() don't work

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#36]
$params = array(
            "method" => "GET",
            "ID" => 41,
);
$mj->newsletterDetailContent($params);

I have this error:
- Unknown resource: "newsletterDetailContent" (cf picture)

![sans titre](https://cloud.githubusercontent.com/assets/10528838/5736555/5798bfce-9bd7-11e4-83e3-9c43783c9470.png)

**Comment by CharlesCollas** [comment]
Hello,

It's probably because you don't have the last wrapper.
Please download the class again and keep me informed.

By the way, we are setting up a composer / packagist to make it clearer.

**Comment by fturk** [comment]
Yes, it's work. Thanks.

mailjet class php is commited 2 days ago. I haven't seen this. Sorry :D

**Comment by CharlesCollas** [comment]
No problem!

Can you please close this issue if your problem is solved?

Thanks!
