### ISSUE TITLE
Probleme filtre function contact() 

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#37]
Je voudrais juste vous signaler un probleme sur la fonction contact()
Le probleme est qu'en paramètre si on met ID en majuscusle ça ne marche pas. 
Pour remedier à cela il faut l'ecrire en miniscule.

Code qui ne marche pas :
$params = array (
        "method" => "GET",
        "ID" => 50
);
$mj->contact($params);

Code qui marche:
$params = array (
        "method" => "GET",
        "id" => 50
);
$mj->contact($params);

Ce problème, je l'ai aperçu en mode debuggage.
De plus ce problème est présent lors de la derniere mise a jour de l'api (mailjet class php)

**Comment by arnaudbreton** [comment]
Bonjour,

Dans votre cas, il faut remplacer `"method" => "GET"` par `"method" => "VIEW"` pour que la mécanique interne du wrapper se déclenche comme prévu.

Est-ce que cela fonctionne dans votre cas ?

**Comment by fturk** [comment]
Oui avec la methode VIEW ça marche, mais je voulais juste signaler qu'avec la method GET le "ID" majuscule ne marchais pas mais par contre en miniscule ça marche.
J'ai eu ce probleème dès que j'ai fait la dernière mise à jour

**Comment by fturk** [comment]
Je voulais savoir comment on fait pour recuperer la liste des domaines autoriser ?

**Comment by arnaudbreton** [comment]
C'est exact, nous avons pris en compte ce problème. Nous le réglerons au plus vite dans une prochaine version.

Si ce problème est résolu, pouvez-vous svp fermer ce ticket en créer un nouveau pour votre autre question ? Merci !

**Comment by fturk** [comment]
ok
