### ISSUE TITLE
Don't work newsletterStatus()

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#38]
La fonction newsletterStatus() ne marche pas mais j'ai trouver la raison, vous l'avez oublier de mettre dans le fichier "php-mailjet-v3-simple.class.php".

Voici la solution que je vous propose:
J'ai ajouter à la ligne 170 :
($resource == "newsletterStatus") ||
et à la ligne 250 :
($resource == "newsletterStatus") ||

Voila ça marche !!!!

**Comment by arnaudbreton** [comment]
Merci de votre retour, le bug est désormais fixé et une version 1.0.1 contenant ce patch a été publiée.

La prochaine fois, n'hésitez pas à nous soumettre une Pull Request, nous serions ravi de l'intégrer à notre code !

**Comment by fturk** [comment]
Derien. Il n'y a pas de soucis, j'y penserai la prochaine fois.
