### ISSUE TITLE
Comment récuperer la liste des domaines autoriser

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#39]
Bonjour,
 
Je voudrais savoir quel fonction qui me permettra de récuiperer la liste des domaines autoriser car j'ai cherche mais je n'ai pas trouver.

Merci,

**Comment by arnaudbreton** [comment]
Par domaine, vous entendez bien les adresses d'envois autorisés, incluant les domaines entiers, n'est-ce pas ? 

Dans ce cas, je vous invite à regarder du côté de http://dev.mailjet.com/email-api/v3/sender/

En espérant avoir répondu à votre question.

**Comment by fturk** [comment]
Oui, mais ça me retourne pas les domaines. 
Voici le résultat qui me retourne:
(J'ai mis des # pour masquer les informations sensibles.)
"Count": 1,
"Data":
[

    {
        "CreatedAt": "2014-11-19T10:14:55Z",
        "DNSID": ######,
        "Email": "#####@####.####",
        "EmailType": "unknown",
        "Filename": "",
        "ID": 1,
        "IsDefaultSender": false,
        "Name": "Default",
        "Status": "Active"
    }

],
"Total": 1

**Comment by arnaudbreton** [comment]
Dans le cas d'un sender ajouté en tant que domaine (*@domaine.com), il apparaîtra sous cette forme dans le champ `Email`. 

Est-ce bien cela que vous recherchez ?

**Comment by fturk** [comment]
Mais du coup je dois splitter pour récuperer le domaine.com ??

**Comment by Simon-Mailjet** [comment]
Bonjour,
En spécifiant le paramètre style=full dans votre requête, l'API vous retournera des informations supplémentaires, dont "Domain": "blabla.com"
Je pense que cela doit coller avec ce que vous attendez :)

**Comment by fturk** [comment]
Merci Simon-Mailjet je suis très content :D.

Je voudrais savoir une chose, où est ce que c'est marquer le paramètre "state=full" :D

**Comment by Simon-Mailjet** [comment]
Possiblement pas encore documenté, ou bien caché :) je remonte le manque de doc à ce sujet, merci pour le retour !

**Comment by fturk** [comment]
Derien et merci encore.
