### ISSUE TITLE
Fonction contactslistsignup() me retourne rien

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#40]
Bonjour,

J'utilise la fonction contactslistsignup() et ça me retourne rien:

#{
#    "Count": 0,
#    "Data": [ ],
#    "Total": 0
#}

Pour tant, j'ai créer mes contacts via la fonction contact(), j'ai créer ma liste via la fonciton contactslist() et j'ai ajouter les contacts à une liste via la fonciton listrecipient().

Et pourtant la fonction contactslistsignup(), me retourn rien ?

Merci,

**Comment by arnaudbreton** [comment]
Bonsoir,

Quelle information souhaitez-vous obtenir ? 
Cette entité sert à récupérer les inscriptions à une liste de contacts par un widget par exemple.

**Comment by fturk** [comment]
Je voudrais avoir la "date d'ajout" d'un contact dans une liste de contact.
J'avais contacter le support mailjet et il m'on répondu que la date d'ajout d'un contact dans une liste de contact correspond à la date de création d'un contact.

**Comment by arnaudbreton** [comment]
Bonjour,

Cette information n'est pas retournée par notre API actuellement. Nous allons investiguer pour la faire remonter.

Nous vous tenons au courant. 
Merci de votre retour.

**Comment by fturk** [comment]
D'accord Merci. Je serai en attente :D

**Comment by arnaudbreton** [comment]
@fturk, nous avons ouvert notre documentation API, visible à https://dev.mailjet.com/guides sur Github, où nous traiterons désormais ce type de question lié à l'usage de l'API plus qu'aux wrappers. Si vous souhaitez obtenir plus d'informations sur votre questions, nous vous invitons à ouvrir une nouvelle discussion sur cet espace.

Le repository de la documentation est visible ici : https://github.com/mailjet/api-documentation
