### ISSUE TITLE
Fonction contactslist() -> Paramètre Sort ne fonctionne pas

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#41]
Je n'arrive pas a trier mes listes de contact. j'ai essayé par l'ID, CreatedAt ... rien ne fonctionne.

**Comment by arnaudbreton** [comment]
Pouvez-vous svp nous en dire plus sur votre besoin, en nous fournissant un exemple de code et en détaillant plus précisément la demande svp ? Merci de votre aide.

**Comment by fturk** [comment]
$params = array(
            "Sort" => "CreatedAt+DESC"  ou "Sort" => "ID+DESC"
            
        );
$mj->contactslist($params);

**Comment by shubs** [comment]
Hey @fturk ,
I am really sorry to tell you that this is a bug on Mailjet's side,
We are working on it and will let you know ASAP.

Best,

**Comment by fturk** [comment]
Hi @shubs , 
it's not a problem, i will wait :D
Thanks

**Comment by florianproxi** [comment]
@fturk solution de secours temporaire: trier son tableau en sens inverse avec array_reverse()

**Comment by fturk** [comment]
@florianproxi oui tkt pas j'ai fais en sorte que je trie mon tableau en sens inverse. Le but de cette issue était de remonter le beug :D mais je te remercie encore :D

**Comment by arnaudbreton** [comment]
Bonjour @fturk,

This issue is now solved on our side.
Could you please confirm it's working for you now?

Thanks for your patience on this.
Best,
Arnaud.
