### ISSUE TITLE
Fonction sender() status active ne marche pas ?

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#42]
Bonjour,

Je n'arrive pas à activer un "sender email", voici mon code:

$params = array (
        "method" => "PUT",
        "ID" => 3,
        "Status" => "Active"
);
$mj->sender($params);

----> [ErrorMessage] => Internal error: MJ19 Setting a value for property "Status" is not allowed

J'ai l'impression qu'on ne peut pas faire via l'API ?

Merci

**Comment by arnaudbreton** [comment]
Bonsoir,

Il n'est effectivement pas possible d'activer un expéditeur en modifiant son `Status` via l'API pour des raisons évidentes de sécurité.

Nous sommes informés d'un bug empêchant l'envoi d'un email de validation lors du passage par l'API. Nous travaillons à sa résolution pour corriger cela au plus vite.

En attendant, je vous invite à ajouter vos expéditeurs directement via l'interface, si cela est possible pour vous ? 

Désolé de la gêne occasionnée.
Nous vous tenons informer de notre avancement dans la résolution de ce problème.

**Comment by fturk** [comment]
Bonjour,

C'est dommage qu'on ne peut pas forcer l'activation. En version 1 on pouvais faire cette manipulation.

Merci encore,

**Comment by arnaudbreton** [comment]
Cela est clairement un bug identifié de notre côté et nous travaillons à sa résolution au plus vite.

Merci de votre patience sur tout cela.

Cordialement,
Arnaud.
