### ISSUE TITLE
Calling the constactslist DELETE method using a unique Email address returns a 405 not allowed message

### ISSUE THREAD

**Issue by bamboolix** [mailjet/mailjet-apiv3-php-simple#45]
I am trying to delete a contact using the contactslist DELETE method. It doesn't seem to work since I keep getting a not allowed eror returned. Would it be possible to get a hint on how to troubleshoot this issue ? Here is the code snippet : 

$this -> m_oMailJet = new Mailjet();

$email_params = array
			(
				'method' => 'DELETE',				
				//'ID' => $mj_list_id,
				'Address' => $email_array
			);
$response_emails =  $this -> m_oMailJet -> contactslist( $email_params );

Regards

**Comment by fturk** [comment]
Hi @bamboolix , write this 4 function in your mailjet class:

public function getId_list($s_nameList){
        $params = array(
            "method" => "GET",
            "Name" => urlencode($s_nameList)
        );
        return $this->contactslist($params)->Data[0]->ID;
 }
public function getIdContact_contact($s_contactEmail){
        $params = array(
            "method"    =>     "VIEW",
            "ID"        =>     $s_contactEmail
        );
        return $this->contact($params)->Data[0]->ID;
}
public function listRecipientID($email,$listID){
        $params = array(
                'method'        => 'GET',
                'ContactsList'  => $listID,
                'ContactEmail'  => $email
        );
        return $this->listrecipient($params);
}

public function deleteContactToList($s_contactEmail, $s_nameList) {
        $i_idList = $this->getId_list($s_nameList);
        $i_idContact = $this->getIdContact_contact($s_contactEmail);
        $result=$this->listRecipientID($s_contactEmail,$i_idList);
        $params = array(
            'method'            => 'DELETE',
            'ContactID'         => $i_idContact,
            'ListID'            => $i_idList,
            'ID'                => $result->Data[0]->ID,            
        );
        $this->listrecipient($params);
}


After write in class mailjet, you use function deleteContactToList($s_contactEmail, $s_nameList),
example:
$mj->deleteContactToList("contact@gmail.com","Name Of Liste");

**Comment by bamboolix** [comment]
thanks for the answer I'm going to try this this afternoon.

I'll keep you posted

**Comment by fturk** [comment]
you're welcome @bamboolix !!! :D

**Comment by bamboolix** [comment]
Unfortunatelly I'm still getting the not allowed error ..

**Comment by fturk** [comment]
you would like delete contact of contactList or just delete contact ?

**Comment by bamboolix** [comment]
Well yes I only need to delete one contact in a list.

**Comment by fturk** [comment]
do you have a skype ?
my skype is:
pokipok73

**Comment by fturk** [comment]
you can put a screen shot of return error and code please?

**Comment by arnaudbreton** [comment]
Thanks @fturk for your help on that, highly appreciated!

In order for these information to be useful to our community, I think it would be better to continue the conversation here instead of private discussions.

Can you please tell us more about the error you got?

As @fturk indicated, to manage the relation between a [`contactslist`](http://dev.mailjet.com/email-api/v3/contactslist/) and a [`contact`](http://dev.mailjet.com/email-api/v3/contact/) you have to use the [`listrecipient`](http://dev.mailjet.com/email-api/v3/listrecipient/) entity.
According to our [documentation](http://dev.mailjet.com/email-api/v3/listrecipient/), since the `listrecipient` ressource has `ContactALT` and `ListALT` properties, you can identify this link by using the contact's email and the list's name (instead of ID).

Regarding that, the `deleteContactToList` function becomes: 
```php
public function deleteContactToList($s_contactEmail, $s_nameList) {
	$params = array(
	'method' => 'DELETE',
		'ContactALT' => s_contactEmail,
		'ListALT' => $s_nameList
	);

	$this->listrecipient($params);
}
```

Please let me know!

**Comment by webiummedia** [comment]
This is what i did to get that part working. You need 2 functions. One to get the email ID and one to delete the email. Works for me.

    function getcontact($email) {
        $mj = new Mailjet();
        $params = array(
            "method" => "VIEW",
            "ContactALT" => "$email",
            "ListID" => "1"
        );
    
        $result = $mj->listrecipient($params);
        $result = json_decode(json_encode($result),true);
    
        if ($mj->_response_code == 201)
           $result[status] == "1";
        else
           $result[status] == "0";
    
        return $result;
    }
    
    function deletecontact($listID, $contactID) {
        $mj = new Mailjet();
        $params = array(
            'method' => 'DELETE',
            'ID' => $contactID,
            'ListID' => $listID
        );
    
        $result = $mj->listrecipient($params);
        $result = json_decode(json_encode($result),true);
    
        if ($mj->_response_code == 201)
           $result[status] = "1";
        else
           $result[status] = "0";
    
        return $result;
    }

    $contact = getcontact($email);        
    $del = deletecontact($list_ID, $contact[Data][0][ID]);

**Comment by bamboolix** [comment]
iss

**Comment by bamboolix** [comment]
issue solved. The prior DELETE method applied to contactslist works. Same for the listrecepient DELETE method. Applying the function to the correct entity solved my issue. Thanks @fturk your solution did it !

**Comment by arnaudbreton** [comment]
Glad to hear it's working for you now! Thanks a lot @fturk for your help, very appreciated!

In your `deletecontact` function, I'm just wondering if there's not a bug since you're using `ID` and not `ContactID` to identify the contact in the params. Can you please check that?

The function should be:
```php
function deletecontact($listID, $contactID) {
    $mj = new Mailjet();
    $params = array(
        'method' => 'DELETE',
        'ContactID' => $contactID,
        'ListID' => $listID
    );

    $result = $mj->listrecipient($params);
    $result = json_decode(json_encode($result),true);

    if ($mj->_response_code == 201)
       $result[status] = "1";
    else
       $result[status] = "0";

    return $result;
}
```

**Comment by bamboolix** [comment]
I did do a few reajustments on fturk's example. So yes instead of ListID it is ID I am using.

**Comment by bamboolix** [comment]
infact here is the array I'm using : 

	$params = array
		(
				'method' => 'DELETE',
				'Address' => $email,			
				'ID' => $result -> Data[ 0 ] ->ID,
		);

**Comment by arnaudbreton** [comment]
To delete a `contactslist`? `ID` should be enough here I think.
