### ISSUE TITLE
Sending a campain from website generated list (not working)

### ISSUE THREAD

**Issue by webiummedia** [mailjet/mailjet-apiv3-php-simple#46]
Hi i created a newsletter registration form on this page for one of my clients.
https://www.paindevie.org/index.php?mod=page&id=155

When the form is used, the email is added to a contact list (Pain de vie (Site Web)) in mailjet. When i try to send a campain to that contact list, it says the campaing was sucessful but no emails is sent out... When i try to download a CSV version of the contact list the CSV is empty. I don't understand ...

[removed]

I created a test list and imported a CSV of a few emails manualy from the mailjet account and tryed to send a mail campaing and it worked. But when i try the one generated by the website no mails are sent out.

[removed]

As you can see in this image it says that the last campain was 21 minutes ago ... but no emails where sent as you can see in the screen of my dashboard... 

[removed]

What is really strange is that when i try to download the list in CSV, the file is empty ... So now i am wandering if i imported my contacts the right way ... This is my PHP code. Let me know if this is an importation issue and where is the error.

    if ($_POST[newsletter_form]){
        if ($_POST[nom]==''){$err[] = 'Vous devez fournir un nom';}
        if ($_POST[courriel]==''){$err[] = 'Vous devez fournir un courriel';}
        if ($_POST[check1]==''){$err[] = 'Vous devez cocher la case pour vous abonner.';}
        if ($_POST[check2]==''){$err[] = 'Vous devez accepter les (Mentions Légales) et la (Politique de confidentialité) pour vous abonner.';}
        if ($_POST[captcha]!=$_SESSION['captcha']['code']){$err[] = 'Vous devez retaper le contenue de l\'image pour prouver que vous êtes bien humain.';}
        
        if (!$err){
            $contact = createContact($_POST[courriel], $_POST[nom]);
            $list = addContactToList($_POST[courriel], 1);
            $result = '1';
        }
    }
    
    if ($_POST[desabonement_form]){
        $contact = getcontact($_POST[courriel_d]);        
        $del = deletecontact(1, $contact[Data][0][ID]);
        $result = '2';
    }
    
    function createContact($Cemail, $Cname) {
        $mj = new Mailjet();
        $params = array(
            "method" => "POST",
            "Email" => $Cemail,
            "Name" => $Cname
        );
    
        $result = $mj->contact($params);
        $result = json_decode(json_encode($result),true);
    
        if ($mj->_response_code == 201)
           $result[status] = "1";
        else
           $result[status] = "0";
    
        return $result;
    }
    
    function addContactToList($email, $listID) {
        $mj = new Mailjet();
        $params = array(
            "method" => "POST",
            "ContactALT" => $email,
            "ListID" => $listID
        );
    
        $result = $mj->listrecipient($params);
        $result = json_decode(json_encode($result),true);
    
        if ($mj->_response_code == 201)
           $result[status] = "1";
        else
           $result[status] = "0";
    
        return $result;
    }
    
    function getcontact($email) {
        $mj = new Mailjet();
        $params = array(
            "method" => "VIEW",
            "ContactALT" => "$email",
            "ListID" => "1"
        );
    
        $result = $mj->listrecipient($params);
        $result = json_decode(json_encode($result),true);
    
        if ($mj->_response_code == 201)
           $result[status] == "1";
        else
           $result[status] == "0";
    
        return $result;
    }
    
    function deletecontact($listID, $contactID) {
        $mj = new Mailjet();
        $params = array(
            'method' => 'DELETE',
            'ID' => $contactID,
            'ListID' => $listID
        );
    
        $result = $mj->listrecipient($params);
        $result = json_decode(json_encode($result),true);
    
        if ($mj->_response_code == 201)
           $result[status] = "1";
        else
           $result[status] = "0";
    
        return $result;
    }

**Comment by arnaudbreton** [comment]
Hi @webiummedia, 

Thanks for reaching out.

First, could you please hide or remove the emails addresses shown in the first screenshot, for privacy reasons? Thanks!

Next, I think your `addContactToList` function is missing the `IsActive` field set to `True`. Otherwise, as indicated in our [documentation](http://dev.mailjet.com/guides/newsletter-guide/), the value is `False` which leads to a full non active contacts list to which we can't send any email.

Hope it helps.
Best.

**Comment by webiummedia** [comment]
I removed the screenshots. Thx i will try that right away.

**Comment by webiummedia** [comment]
It would a been helpful to have a visuel sign in the contact list to see that they where inactive. A grey dot for exemple and when you hover it it would give a hint (Status inactive). That would of helped me out a lot. I have a question. Why do we need (Active | Inactive) when we have (Subscribe | Unsubscribe)?

**Comment by arnaudbreton** [comment]
@webiummedia, your feedback are fair and already taken in account by our product team for a coming release.

> Why do we need (Active | Inactive) when we have (Subscribe | Unsubscribe)?
Agreed it's a subtile difference in your case but it's needed in some cases.
In a future release of our API, the `IsActive` value is set to true by default.

Is it working for you now? 
Thanks for your patience.

**Comment by webiummedia** [comment]
Thx Arnaud,

Not yet ... it seems my update is not working
    function updateContactToList($email, $listID) {
        
        $mj = new Mailjet();
        
        // Try update if case creation fails
        $params = array(
            "method" => "UPDATE",
            "ContactALT" => $email,
            "ListID" => $listID,
            "IsActive" => true,
            "IsUnsubscribed" => false
        );
    
        $result = $mj->listrecipient($params);
        $result = json_decode(json_encode($result),true);
    
        return $result;
    }

The contact does not turn active.

**Comment by arnaudbreton** [comment]
What is the return code of that call?

**Comment by webiummedia** [comment]
When i try to create the email i get
[ErrorMessage] => MJ18 A Contact resource with value "***@gmail.com" for Email already exists.

When i try to add it to the list i get
[ErrorMessage] => A duplicate ListRecipient already exists.

When i try to update it i get

Resource: listrecipient
Request type: POST
Get Arguments: (NONE)

Post Arguments
ContactALT = ***@gmail.com
ListID = 1
IsActive = 1
IsUnsubscribed =

Call url	https://api.mailjet.com/v3/REST/listrecipient

But when i try to download the list of emails from the CSV the ***@gmail.com is not in the list.

**Comment by arnaudbreton** [comment]
To update you need to retrieve the ID of the ListRecipient you want to update.

To achieve that you can use the filters, as described on our [documentation](http://dev.mailjet.com/email-api/v3/listrecipient/).

**Comment by webiummedia** [comment]
What is the diffrence between ContactID and ID? and if ID is not ContactID, where do i get it?

**Comment by fturk** [comment]
ID represent id of listrecipient, and ContactID represent id of contact

**Comment by webiummedia** [comment]
Why do we need to provide that for an update ... the ContactID or ContactALT should be all he needs considering the ContactID is supose to be unic in that list. Normaly you should be able to make a query without needing the ID ...

So how do i get the ID i need?

**Comment by fturk** [comment]
Tu n'arrive pas a faire un UPDATE d'un contact dans une liste ?

**Comment by webiummedia** [comment]
non ça marche pas ... J'essaye de changer les courriel de ma liste en "active" mais le changement ne s'opère pas ... Pourtant ça ne retourne pas d'erreur dans le dubug. Quand je vais dans ma liste sur le site de mailjet et que je veux télécharger le CSV des courriels de la liste il me retourne seulement que 3 courriel sur 170. (3 que j'ai ajouter moi même). Les 167 autres on été ajouter via un script mais j'ai pas spécifier que je voulais qu'il soit actif ... et la j'arrive plus a changer leur status. En plus je vois pas de place pour le faire depuis le site non plus.

**Comment by fturk** [comment]
tu veut les mettres en actif les 167 autres ?

**Comment by webiummedia** [comment]
Oui donc j'essaye de faire un update sur chaque courriel

        function updateContactToList($email, $listID) {
            
            $mj = new Mailjet();
            
            // Try update if case creation fails
            $params = array(
                "method" => "UPDATE",
                "ContactALT" => $email,
                "ListID" => $listID,
                "IsActive" => true,
                "IsUnsubscribed" => false
            );
        
            $result = $mj->listrecipient($params);
            $result = json_decode(json_encode($result),true);
        
            return $result;
        }

**Comment by fturk** [comment]
Deja pour faire un UPDATE, il faut utiliser la methode PUT

**Comment by webiummedia** [comment]
![capture6](https://cloud.githubusercontent.com/assets/4869819/5965107/85bd850a-a7c7-11e4-92b0-8d402edd8319.PNG)

Ya pas PUT dans les methode

**Comment by fturk** [comment]
Il faut bien lire regarde ce que j'ai encadrer,
![sans titre](https://cloud.githubusercontent.com/assets/10528838/5965151/18c46d28-a7fa-11e4-8d85-0a84765c6aa9.png)

**Comment by fturk** [comment]
Essaie avec PUT ça va aller beaucoup mieux :D

**Comment by webiummedia** [comment]
wow je l'ai complètement manquer celui la ... a leur place je metrais la methode a utiliser dans le titre ... c'est pas évidant lol Bon j'ai changer mais j'ai toujours le même problème le contact n'est pas dans la liste du CSV

Quand j'ouvre la liste de contact et que je clique sur le contact que je veux rendre actif j'ai remarquer que ça dit qu'il fait partie d'aucune liste .... pourtant il est bien dedans

![capture7](https://cloud.githubusercontent.com/assets/4869819/5965320/57363c70-a7c9-11e4-966d-df225efd369c.PNG)

**Comment by fturk** [comment]
function listrecipient tu arrive a voir qu'il est inactif ?

**Comment by fturk** [comment]
essaie ça:

$params = array(
            "method" => "GET",
            "ContactsList" => $listID,
            "Active" => 0            
);
var_dump($mj->listrecipient($params));


Si tu fais ça tu récupere la liste des contacts non actif d'une liste

**Comment by fturk** [comment]
Tiens execute ça en n'oubliant pas de remplacer $listID:


        $params = array(
            "method" => "GET",
            "ContactsList" => $listID,
            "Active" => 0            
        );
        $a = $mj->listrecipient($params)->Data;
        
        foreach($a as $value){
            $params = array(
                "method" => "PUT",
                "ID" => $value->ID,
                "IsActive" => true
            );
            $mj->listrecipient($params);
        }

**Comment by webiummedia** [comment]
parfait je test toute suite merci

**Comment by webiummedia** [comment]
non toujours pas ... je comprend pas pourquoi ça ne fonctionne pas ... En fin de compte j'ai supprimer la liste puis importer manuelement chaque utilisateur via l'importantion de CSV

J'ai fait ce script pour me generer la liste.

    echo "email;name<br />"; 
    $SELECT = mysql_query("SELECT * FROM membre");
    while($m=mysql_fetch_array($SELECT)){
        $nom = ucfirst(strtolower($m[prenom]))." ".ucfirst(strtolower($m[nom]));
        echo "$m[pseudo];$nom<br />";   
    }

Quand je télécharge le CSV tout les mail y sont ... Je pense que le bug est du côté de mailjet. Plusieurs des essay que j'ai fait aurais du marcher la dernière exemple que tu m'a donner.

**Comment by fturk** [comment]
Demain je te donnerai les fonctions pour résoudre ton problème.

PS: mon skype est                    pokipok73

**Comment by fturk** [comment]
Salut @webiummedia, alors tu as résolé ton problème ?

**Comment by GuillaumeBadi** [comment]
### Hey @webiummedia :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
