### ISSUE TITLE
$request  = POST but $this->_response_code = 200 ?

### ISSUE THREAD

**Issue by VaN-dev** [mailjet/mailjet-apiv3-php-simple#47]
Hello,

I'm using this PHP wrapper for Mailjet API. When trying to deal with return value from API, I found something strange in the sendRequest() method.
My requests are made with POST, and the response code from CURL is 200. And the sendRequest() doesn't deal with this test correctly :
```
if ($request == 'POST') {
    return ($this->_response_code == 201) ? true : false;
}
if ($request == 'DELETE') {
    return ($this->_response_code == 204) ? true : false;
}
return ($this->_response_code == 200) ? true : false;
```
Accordingly to this code from the sendRequest() method, it returns false, although everything worked fine.

Shouldn't you edit the method with 
```
if ($request == 'POST') {
    return ($this->_response_code == 200 || $this->_response_code == 201) ? true : false;
}
```

**Comment by GuillaumeBadi** [comment]
### Hey @VaN-dev :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
