### ISSUE TITLE
on Internet Explorer the IFrame doesn't display, unless clients reduce the internet security options

### ISSUE THREAD

**Issue by bamboolix** [mailjet/mailjet-apiv3-php-simple#48]
I have noticed and sent a message about this issue. On Internet explorer due to controls over P3P header policy, the Mailjet IFRAME doesn't display, unless one reduces his internet options security. 
It is a problem when your users do not want to sacrifice their security to display an IFRAME. It is just a matter of setting the right P3P headers is the requests answer.

**Comment by arnaudbreton** [comment]
Thanks for pointing that out.

I take good note of that and will see to fix it ASAP with my team. 
Is it something affecting all the versions of IE?

Thanks!

**Comment by arnaudbreton** [comment]
Hi @bamboolix, we released a fix. Can you please confirm it's working for you now? Thanks for your patience.

**Comment by bamboolix** [comment]
Hi @arnaudbreton great to hear this. It works fine on my side.

Best regards.

David

**Comment by arnaudbreton** [comment]
Glad to hear it works for you! 

Could you please close this issue if you have no further questions? Thanks!

**Comment by bamboolix** [comment]
No more questions. 

I'm closing the Topic
