### ISSUE TITLE
Fonction listContacts et AJax

### ISSUE THREAD

**Issue by Tomenbois** [mailjet/mailjet-apiv3-php-simple#49]
Bonjour,

Je commence juste à me servir de l'API, je veux récupérer une simple liste des contacts.
Mais je n'arrive pas à comprendre ce que je récupère avec cette fonction : 

    function listContacts()
    {
        $mj = new Mailjet();
        $result = $mj->contact();

         if ($mj->_response_code == 200)
           echo "success - listed contacts";
        else
           echo "error - ".$mj->_response_code;

        return $result;
    }

$result est un JSON ?

Parce que si oui mon code ci dessous n'apprécie pas.

    function listContact(){
        $.ajax({
            type:'POST',
            url: 'Mailjet/mailjetapi.php',
            dataType :'json',
            data: {func : 'listContact', idchef: idchef},
            success: function (data) {
                window.alert('good !!');
            },
            error : function(){
                window.alert('error mailjet');
            }
        });
    }

Pouvez vous m'aiguiller svp ?

**Comment by webiummedia** [comment]
Salut,
ton approche n'est pas bonne. de la façon que tu veux le faire, tu va devoir passer a l'api ton $MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE. EN claire, ils serons lisible dans la source de ta page ... c'est préférable que tu appelle une page local qui va ensuite appller l'api en PHP. De cette mannière tes clés reste invisible. Ex:

        var data = "listcontacts=1";
        $.ajax({
            url: 'ajax.php',
            type: 'POST',
            data: data,
            cache: false,
            processData: false,
            contentType: false,
            success: function(data, textStatus, jqXHR){
                
                var data = $.parseJSON(data);

                window.alert(data);
              
            },
            error: function(jqXHR, textStatus, errorMessage) {
               window.alert('error mailjet');
            }
        }); 

Ensuite dans ton PHP:

    <?php
    
    if ($_GET[listcontacts]=="1"){
        $listID = 1;
        echo listcontacts($listID);
    }
    
    function listcontacts($listID){
        
        $mj = new Mailjet();
        $params = array(
            "method" => "GET",
            "ContactsList" => $listID        
        );
        $a = $mj->listrecipient($params)->Data;
        
    }
    
    ?>

**Comment by webiummedia** [comment]
Si le problème est régler, peux-tu fermer le issue?

**Comment by Tomenbois** [comment]
Bonjour,
désolé du temps que j'ai mis pour vous répondre.
Le problème n'est pas réglé.
J'ai utilisé le code que vous m'avez proposé. Il se trouve que data me retourne NULL.

Quand j'utilisais la fonction 

    $mj->contact();

data me retournais ceci : 

    object(stdClass)#2 (3) {
        ["Count"]=> int(2) 
        ["Data"]=> array(2) { 
            [0]=> object(stdClass)#3 (11) { 
                ["CreatedAt"]=> string(20) "2015-01-26T11:12:47Z" 
                ["DeliveredCount"]=> int(5) 
                ["Email"]=> string(20) "t*******s@hotmail.fr" 
                ["ID"]=> int(1) 
                ["IsOptInPending"]=> bool(false) 
                ["IsSpamComplaining"]=> bool(false) 
                ["LastActivityAt"]=> string(20) "2015-01-26T15:15:46Z" 
                ["LastUpdateAt"]=> string(20) "2015-01-26T11:12:47Z" 
                ["Name"]=> string(0) "" 
                ["UnsubscribedAt"]=> string(0) "" 
                ["UnsubscribedBy"]=> string(0) "" 
            } 
            [1]=> object(stdClass)#4 (11) { 
                ["CreatedAt"]=> string(20) "2015-01-26T14:07:42Z" 
                ["DeliveredCount"]=> int(0) 
                ["Email"]=> string(20) "d**********o@free.fr" 
                ["ID"]=> int(2) 
                ["IsOptInPending"]=> bool(false) 
                ["IsSpamComplaining"]=> bool(false) 
                ["LastActivityAt"]=> string(20) "2015-01-26T14:18:19Z" 
                ["LastUpdateAt"]=> string(20) "2015-01-26T14:07:42Z" 
                ["Name"]=> string(0) "" 
                ["UnsubscribedAt"]=> string(0) "" 
                ["UnsubscribedBy"]=> string(0) "" 
             } 
        } 
        ["Total"]=> int(2) 
    }

Ce qui semble plutôt clair, c'est un json. Mais ajax n'avais pas l'air d'apprecier car il passait tout le temps dans le error.

**Comment by arnaudbreton** [comment]
Bonjour,

Pouvez-vous mettre `method` à `VIEW` plutôt qu'à `GET` et me dire si cela fonctionne ? Merci.

**Comment by Tomenbois** [comment]
ça ne change rien, data est toujours à NULL.

**Comment by Tomenbois** [comment]
Apparement le `if($_POST['listcontacts'] == "1")` ne fonctionne pas, du coup je l'ai commenté et j'ai eu des retours.

Pour tester j'ai dans mon mailjetapi.php : 
```
<?php
    include("php-mailjet-v3-simple.class.php");
    $listID = 1;
    echo listcontacts($listID);

    function listcontacts($listID){

        $mj = new Mailjet();
        $params = array(
            "method" => "VIEW",
            "ListID" => $listID        
        );
        $a = $mj->listrecipient($params)->Data[0]; //Il faut aussi ajouter ['indice'] car c'est un Array.
        return $a;
    }
```
et dans mon ajax_mailjet.js
```
function listContact(){
    var data = "listcontacts=1";
    $.ajax({
        url: 'Mailjet/mailjetapi.php',
        type: 'POST',
        data: data,
        cache: false,
        processData: false,
        contentType: false,
        success: function(data, textStatus, jqXHR){

            //var data = $.parseJSON(data);

            window.alert(data);

        },
        error: function(jqXHR, textStatus, errorMessage) {
           window.alert('error mailjet : '+errorMessage);
        }
    }); 

}
```
Avec `echo` j'ai data qui retourne : 
```<br />
<b>Catchable fatal error</b>:  Object of class stdClass could not be converted to string in <b>/.../Mailjet/mailjetapi.php</b> on line <b>12</b><br />```

Si je remplace `echo` par `var_dump` j'ai : 
```
object(stdClass)#3 (7) {
["ContactID"]=>int(1)
["ID"]=>int(1)
["IsActive"]=>bool(true)
["IsUnsubscribed"]=>bool(false)
["ListID"]=>int(1)
["ListName"]=>string(21) "Liste d'envoi de test"
["UnsubscribedAt"]=>string(0) ""
}
```

A partir de là, je me dit que je vais décommenter la ligne `//var data = $.parseJSON(data);`

Une belle erreur apparaît : `Uncaught SyntaxError: Unexpected token o`.

**Comment by arnaudbreton** [comment]
Je pense que tu devrais faire ` echo json_encode(listcontacts($listID));` car autrement tu essayes de sérialiser un objet (`stdClass`) en string d'où ton erreur.

**Comment by fturk** [comment]
Salut @Tomenbois 
Tu veut récuperer quoi en résultat de ta fonction ??

**Comment by Tomenbois** [comment]
Salut à tous,

Alors voilà j'ai réussi à récupérer et à lire le Json.

Voilà le code : 
Dans mailjetpi.php
```
<?php
    include("php-mailjet-v3-simple.class.php");
    $listID = 1;
    echo json_encode(listcontacts($listID));

    function listcontacts($listID){

        $mj = new Mailjet();
        $params = array(
            "method" => "VIEW",
            "ListID" => $listID        
        );
        $a = $mj->listrecipient($params)->Data[0]; //Il faut aussi ajouter ['indice'] car c'est un Array.
        return $a;
    }
```

Dans ajax_mailjet.js
```
function listContact(){
    var data = "listcontacts=1";
    $.ajax({
        url: 'Mailjet/mailjetapi.php',
        type: 'POST',
        data: data,
        cache: false,
        processData: false,
        contentType: false,
        success: function(data, textStatus, jqXHR){

            //var data = $.parseJSON(data);

            window.alert(data.ListName);

        },
        error: function(jqXHR, textStatus, errorMessage) {
           window.alert('error mailjet : '+errorMessage);
        }
    }); 

}
```
 Là j'ai dans mon alert le nom de ma liste.
C'est bien !

Ce que je voulais à l'origine c'est la liste des contacts (les adresses mails quoi !) et pas le nom des listes. Mais le problème est le même.
J'ai changé `$a = $mj->listrecipient($params)->Data[0];` par `$a = $mj->contact();` dans le mailjetapi.php et `window.alert(data.ListName);` par `window.alert(data.Data[0].Email);`

Merci à tous pour votre aide !

**Comment by fturk** [comment]
C'est bon tu as tes liste de contact ?

**Comment by arnaudbreton** [comment]
@Tomenbois pour récupérer les contacts faisant partis d'une liste précise, tu dois appeler la ressource [`contact`](http://dev.mailjet.com/email-api/v3/contact/) avec le filtre `ContactsList`.

Un exemple:
```php
<?
include('php-mailjet-v3-simple.class.php');
$mj = new Mailjet('MJ_API_KEY','MJ_API_SECRET');
$params = array(
    'method' => 'GET',
    'ContactsList' => 1
);
var_dump($mj->contact($params));
```

Cela te renverra un ensemble de [`contact`](http://dev.mailjet.com/email-api/v3/contact/) avec pour chacun, l'email que tu recherches.

**Comment by Tomenbois** [comment]
@fturk Oui merci j'ai eu ce que je voulais.

@arnaudbreton Ok, merci pour cette précision.

Je vais clore cette discussion.

Merci à tous

**Comment by arnaudbreton** [comment]
Avec plaisir, merci pour tes retours. N'hésite pas si tu as d'autres questions.
