### ISSUE TITLE
schedule a contact list csv import

### ISSUE THREAD

**Issue by gorgorbhey** [mailjet/mailjet-apiv3-php-simple#51]

**Comment by arnaudbreton** [comment]
Have you solved your issue?

**Comment by gorgorbhey** [comment]
oui c'est bon. j'avais juste un problème dans le tableau de paramètres de la méthode batchjob (au niveau de method (majuscule/minuscule)
        $params = array( 
            "method" => "POST",
            "JobType" => "Contact list import csv",
            "DataID" => $idfichier,
            "Status" => "upload",
            "RefId" => $id_cible,
            "Method" => "addnoforce",
            "ErrTreshold" => "9",
            "APIKeyID" => $id_apikey,
            "RequestAt" => $requestat
        );

**Comment by GuillaumeBadi** [comment]
### Hey @gorgorbhey :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
