### ISSUE TITLE
Need help for getting contacts by email

### ISSUE THREAD

**Issue by wfabian** [mailjet/mailjet-apiv3-php-simple#52]
Hi,
i've already read the issue #43 because i have the same problem.
I'm trying to write a little sync script.

This is my function to get the contacts:

function mailjetGetContactsByEmail(Mailjet $mj, $email) {
    $params = array(
        "method" => "VIEW",
        "Email" => $email
    );
    $contact = $mj->contact($params);

    // If it worked we should have an ID
    if ($contact->Data[0]->ID){
        // Use the ID to add the user to list 1
        echo "yes";
    }else{
        // Create the contact
        echo "no";
    }
}  

( Sorry, not all of my code were marked as code )

I'm giving the mailjet-object and the email-adress to the function.
But if the e-mail-adresse doen't exist, I'm getting the first contacts of my mailjet-account (id 1-10)

What I like to do is, checking if an account with the given email-adress already exists. If not I like to create the contact. After the check I need the ID of contact to add the contact to a list.

Can anyone help?

Hope you will understand my wonderful english :-)

**Comment by wfabian** [comment]
If i try "GET" as method, i'm getting the same response with the first 10 addresses.
I get the first 10 addresses if the email-address exists.

I always get the same response from mailjet with the first 10 addresses.

**Comment by hristo-todorov** [comment]
Hi @wfabian,

There's a small modification to the code in order to work properly and here it is:

```php
function mailjetGetContactsByEmail(Mailjet $mj, $email) {
	$params = array(
		"method" => "VIEW",
		"ID" => $email
	);
	
	$contact = $mj->contact($params);

	// If it worked we should have an ID
	if ($contact->Data[0]->ID){
		// Use the ID to add the user to list 1
		echo "yes";
	}else{
		// Create the contact
		echo "no";
	}
}
```

Instead of using "Email" you have to use "ID", as it's a unique property. Unique properties are like IDs.

I hope this helps. Don't hesitate to contact me for more help.

**Comment by wfabian** [comment]
Hi,
thank's a lot.
It solved my problem
