### ISSUE TITLE
Emails return id as float causes rounding error

### ISSUE THREAD

**Issue by edwinPhd** [mailjet/mailjet-apiv3-php-simple#54]
recommend you replace 

$this->_response = json_decode($buffer);
with 
$this->_response = json_decode($buffer, false, 512, JSON_BIGINT_AS_STRING);
on line 293

as otherwise your email id's are rounded up after sending an email.

**Comment by arnaudbreton** [comment]
Hey @edwinPhd, thanks for this recommandation. 
If would be awesome if you could open a PR with this change :)! Otherwise, we'll do it by ourselves obviously.

Thanks!

**Comment by arnaudbreton** [comment]
Release https://github.com/mailjet/mailjet-apiv3-php-simple/releases/tag/v1.0.4 includes the fix. Thanks again for your contribution @edwinPhd!
