### ISSUE TITLE
Upload csv into list

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#56]
Hello,
I'm trying to upload a csv to a list using Mailjet Api V3, but not find how to do this.
This is my actually function that didn't work:
public function importerCsv(){
        $params = array(
                        "method"        => "POST",
                        "ID"            => "9",
                        "csv_content"   =>  '"email" "email1@domaine.com" "email1@domaine.com"',
        );
        $result = $this->mj->uploadCSVContactslistData($params);
        var_dump($result);
        var_dump($this->mj->debug());
    }

**Comment by fturk** [comment]
Est ce que tu as la dernière version de la class mailjet ?

**Comment by arnaudbreton** [comment]
Bonne question @fturk!

Je ne suis pas sûr non plus du format du CSV, il n'y pas de saut de ligne. Pouvez-vous essayer d'ajouter des `\n` à la place des espaces ? Autrement, créer un fichier csv à côté, bien formatté et le lire via [file_get_contents en PHP](http://php.net/manual/en/function.file-get-contents.php)

**Comment by fturk** [comment]
@arnaudbreton il y a une explication sur la fonction uploadCSVContactslistData() ?

**Comment by arnaudbreton** [comment]
Nous l'avons ajouté pour un de nos clients, mais nous allons prochainement sortir une nouvelle API pour la gestion des contacts qui permettra de s'affranchir de tout cela. Cette sortie étant très proche, nous pensons donc qu'il n'est pas très pertinent de documenter cette méthode, qui deviendra obsolète (bien que conservé bien évidemment pour la comptabilité).

**Comment by fturk** [comment]
essaie ça :

$params = array(
"method" => "POST",
"ID" => "9",
"csv_content" => "michot.g@mail.com,vincent.dupont@voili.com"',
);

**Comment by arnaudbreton** [comment]
@fturk Ici encore, ton CSV n'est pas correct. Tu décris un enregistrement avec 2 emails, or tu veux plutôt: 

```csv
email1@mailjet.com
email2@mailjet.com
```

Aussi, pouvez-vous svp modifier vos commentaires @fturk @florianproxi pour anonymiser les emails? Merci !

**Comment by fturk** [comment]
@arnaudbreton moi ça marcher.

**Comment by arnaudbreton** [comment]
Tu as bien deux emails importés?

**Comment by fturk** [comment]
Ba en faite la fonction uploadCSVContactslistData() me renvoie un ID

**Comment by arnaudbreton** [comment]
Oui, mais tu es bien d'accord que ce que tu cherches à faire au final est importé ton CSV, n'est-ce pas ? 

Ici, l'upload CSV va fonctionner car le CSV est valide mais l'import ne fonctionnera comme tu l'attends.

**Comment by fturk** [comment]
Du coup avec cette ID, il faut que j'utililise csvimport ?

**Comment by fturk** [comment]
si je fais comme ça :

$params = array(
"method" => "POST",
"ID" => "9",
"csv_content" => "test_1@gmail.com\ntest_2@gmail.com"',
);

**Comment by arnaudbreton** [comment]
Oui, voici un script fonctionnel pour ce scénario:

```php<?php
include("php-mailjet-v3-simple.class.php");

function handleResponse($mj) {
    if ($mj->_response_code >= 200 && $mj->_response_code < 300) {
        print "success\n";
        return true;
    }
    else {
        print "error - ".$mj->_response_code."\n";
        return false;
    }
}

function createContactsLists($mj, $name) {
    $params = array(
        "method" => "POST",
        "Name" => $name,
    );

    $result = $mj->contactslist($params);

    handleResponse($mj);

    return $result->Data[0]->ID;
}

function uploadCSVContactslistData($mj, $listID, $CSVContent) {
    $params = array(
        "method" => "POST",
        "ID" => $listID,
        "csv_content" => $CSVContent
    );

    $result = $mj->uploadCSVContactslistData($params);

    handleResponse($mj);

    return $result->ID;
}

function importCSVContactslistData($mj, $listID, $dataID) {
    $params = array(
        "method" => "POST",
        "ContactsListID" => $listID,
        "DataID" => $dataID,
        "Method" => "addnoforce"
    );

    $result = $mj->csvimport($params);

    handleResponse($mj);

    return $result;
}



$apiKey = "";
$apiSecret = "";

$mj = new Mailjet($apiKey, $apiSecret);
$listID = createContactsLists($mj, "idevnews contacts list");
$dataID = uploadCSVContactslistData($mj, $listID, file_get_contents('test.csv'));
importCSVContactslistData($mj, $listID, $dataID);
```

Avec le CSV suivant: 

```csv
abreton@mailjet.com
```

**Comment by fturk** [comment]
$params = array(
            "method" => "POST",
            "ID" => 49,
            "csv_content" => "test_1@gmail.com\ntest_2@gmail.com"
);
$ida = $mj->uploadCSVContactslistData($params)->ID;

$params = array(
            "method" => "POST",
            "DataID" => $ida,
            "ContactsListID" => 49,
            "Method" => "addnoforce"
);

En fait il me manquait le paramètre "Method" => "addnoforce" et ça fonctionne maintenant :D

**Comment by arnaudbreton** [comment]
Super @fturk! Espérons que ça réponde au problème de @florianproxi également :)

**Comment by fturk** [comment]
Oui c'est sur :D @arnaudbreton

**Comment by florianproxi** [comment]
@fturk Merci, je vais tester cela dans l'aprem :) Je vous tiens au jus.

**Comment by florianproxi** [comment]
@fturk @arnaudbreton Donc la méthode de fturk fonctionne bien, combinée au file_get_contents("fichier.csv")
Mais quand je met en colonne B du csv un champ personnalisé ca n'importe plus.

**Comment by arnaudbreton** [comment]
Peux-tu nous donner un exemple de CSV, aussi, le retour de 
`curl --user "" https://api.mailjet.com/v3/DATA/BatchJob/:job_id/CSVError/text:csv` où `job_id` correspond à l'ID de ton BatchJob. Merci

**Comment by florianproxi** [comment]
@arnaudbreton je n'utilise pas de batchjob mais la méthode uploadCSVContactslistData() suivi de csvimport() comme @fturk décrit plus haut.

**Comment by florianproxi** [comment]
Voici le CSV que j'importe : http://sendbox.fr/pro/utdd92ibwx3c/test.csv.html

**Comment by arnaudbreton** [comment]
Après l'upload, tu utilises un batchjob pour importer, exact?

**Comment by arnaudbreton** [comment]
Je ne parviens pas à accéder à ton lien.

Peux-tu l'anonymiser et le copier ici stp ?

**Comment by florianproxi** [comment]
Voici le retour du batchjob:
stdClass Object
(
    [ErrorInfo] => 
    [ErrorMessage] => Invalid json input: expected ",", but found "7" at stream position 9 ...{"Data":7|8}...
    [StatusCode] => 400
)

Lien du csv: http://dl.free.fr/iR0Qbbd8M

**Comment by arnaudbreton** [comment]
Plusieurs soucis ici: 
* Le séparateur n'est pas une ","
* Les données ne sont pas échapées (mis entre " + échappement des " à l'intérieur)

**Comment by florianproxi** [comment]
Pourtant j'enregistre via excel en format CSV séparateur

**Comment by florianproxi** [comment]
Avez vous un exemple de csv qui fonctionne que je test ?

**Comment by arnaudbreton** [comment]
En voici un oui:

```csv
email1@mailjet.com
email2@mailjet.com
email3@mailjet.com
```

**Comment by florianproxi** [comment]
Et celui qui suit est censé fonctionner ?
"email","codeidbateaux"
"test1@sfr.fr","BTX001"

**Comment by arnaudbreton** [comment]
Oui il semble correct. Si la propriété `codeidbateaux` n'existe pas `csvimport` la créeera.

**Comment by florianproxi** [comment]
Quand je lui envoie ceci: "csv_content"   =>  '"email","codeidbateaux" "test1@sfr.fr","BTX001"',
Il me crée deux propriétés:
- codeidbateaux test1@sfr.fr
- btx001

**Comment by arnaudbreton** [comment]
Dans cet exemple, il manque le saut de ligne `\n`

**Comment by florianproxi** [comment]
Et si je met : "csv_content"   =>  '"email","codeidbateaux"\n"test1@sfr.fr","BTX001"',
Il m'importer en email : codeidbateaux\ntest1@sfr.fr

**Comment by florianproxi** [comment]
Bonjour à tous,
J'espère que vous avez passé un bon week end ? 
Donc j'ai retenté le coup ce week end, sans succès...

**Comment by fturk** [comment]
Salut,

Oui merci et toi ? :D

Essaie ça:

"csv_content" => "email,codeidbateaux\ntest_1@gmail.com,\ntest_2@gmail.com,\n"

Dit moi ?

**Comment by shubs** [comment]
Hello @florianproxi et @fturk 

Je viens d'essayer avec
```
"csv_content" => "email,codeidbateaux\ntest_1@gmail.com,B123\ntest_2@gmail.com,B456\n"
```
Et Je confirme que ça fonctionne chez moi.

Le code finale reste le meme que @arnaudbreton a donné : 
```
<?php
include("php-mailjet-v3-simple.class.php");

function handleResponse($mj) {
    if ($mj->_response_code >= 200 && $mj->_response_code < 300) {
        print "success\n";
        return true;
    }
    else {
        print "error - ".$mj->_response_code."\n";
        return false;
    }
}

function createContactsLists($mj, $name) {
    $params = array(
        "method" => "POST",
        "Name" => $name,
    );

    $result = $mj->contactslist($params);

    handleResponse($mj);

    return $result->Data[0]->ID;
}

function uploadCSVContactslistData($mj, $listID, $CSVContent) {
    $params = array(
        "method" => "POST",
        "ID" => $listID,
        "csv_content" => $CSVContent
    );

    $result = $mj->uploadCSVContactslistData($params);

    handleResponse($mj);

    return $result->ID;
}

function importCSVContactslistData($mj, $listID, $dataID) {
    $params = array(
        "method" => "POST",
        "ContactsListID" => $listID,
        "DataID" => $dataID,
        "Method" => "addnoforce"
    );

    $result = $mj->csvimport($params);

    handleResponse($mj);

    return $result;
}



$apiKey = "";
$apiSecret = "";

$mj = new Mailjet($apiKey, $apiSecret);
$listID = createContactsLists($mj, "idevnews contacts list");
$dataID = uploadCSVContactslistData($mj, $listID, file_get_contents('test.csv'));
importCSVContactslistData($mj, $listID, $dataID);
```
Avec Comme fichier CSV
http://dl.free.fr/bEt46T8iO

**Comment by florianproxi** [comment]
@shubs Hello, merci de l'aide. Donc je viens d'essayer, quand je met email,codeidbateaux\nadzadzaefezgf@orange.fr,BTX999\n directement dans mes paramètres ca fonctionne.
Dès que je met cette chaine dans une variable, ca ne fonctionne plus... Pas logique. Une idée ?

Merci

**Comment by fturk** [comment]
si tu fais un echo de ta variable pour voir ce qu'il affiche

**Comment by florianproxi** [comment]
Il m'affiche le contenu cité.

**Comment by florianproxi** [comment]
Problème résolu, donc en fait j'ai trouvé ca venait de mon str_replace() qui lors du traitement du csv remplacait des caractères en les entourant de '' au lieu de "", truc con quoi...

**Comment by fturk** [comment]
ok nickel :D !!

**Comment by shubs** [comment]
@florianproxi Super que tu ai ressui ! 
Tu peux close cette issue du coup ? :)

PS : Merci à tout le monde pour le coup de pouce
