### ISSUE TITLE
Créer contact avec valeurs champs personnalisées

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#57]
Bonjour à tous,
Comme beaucoup je suis confronté au problème du manque de documentation de l'API Mailjet V3.
Voici ma fonction d'ajout de contact:
public function creerContact() {
        $params = array(
                        "method"    => "POST",
                        "Email"     => uniqid()."@sfr.fr",
        );

        $result = $this->mj->contact($params);

        var_dump($this->mj->_response_code);
        var_dump($result);
    }

Une idée comment également alimenter mes champs personnalisés créés au préalable, par exemple nom et prénom ?

Merci :)

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi, 

Je vous invite à lire notre guide sur le sujet: http://dev.mailjet.com/guides/personalisation-guide/

En espérant que cela répond à votre question.

Je reste à votre disposition,
Arnaud.

**Comment by florianproxi** [comment]
Bonjour Arnaud,

Déjà lu et relu, sans succès....

$data = array(array('Name' => 'societe', 'Value' => 'PROXI'));
    $params = array(
                        'method' => 'PUT',
                        'ID' => 20,
                        'Data' => $data,
    );

    $result = $mj->contactdata($params);

Ca me répond ceci: Invalid key name: "societe"
Alors que ma propriété societe existe ! D'où peut venir le soucis ?

Merci

**Comment by fturk** [comment]
essaie avec la method POST $mj->contactdata($params);

**Comment by arnaudbreton** [comment]
Pouvez-vous me donner le résultat de `contactmetadata` svp?

**Comment by florianproxi** [comment]
Voilà le résultat d'ajout d'une variable "testvar":
Success	
Status code	201
Response	

stdClass Object
(
    [Count] => 1
    [Data] => Array
        (
            [0] => stdClass Object
                (
                    [Datatype] => str
                    [ID] => 12
                    [Name] => testvar
                    [NameSpace] => historic
                )

        )

    [Total] => 1
)

API config	
Protocole	https
Host	api.mailjet.com
Version	v3
Call infos	
Resource	contactmetadata
Request type	POST
Get Arguments	
Post Arguments	Datatype = Str
Name = Testvar
NameSpace = historic
Call url	https://api.mailjet.com/v3/REST/contactmetadata

**Comment by florianproxi** [comment]
@fturk Avec POST, j'obtiens cette erreur: "[ErrorMessage] => Internal error: MJ19 Setting a value for property "ID" is not allowed"

**Comment by arnaudbreton** [comment]
Je parlais d'un GET sur `contactmetadata`, pas d'un POST

**Comment by florianproxi** [comment]
{ "Count" : 2, "Data" : [{ "Datatype" : "str", "ID" : 11, "Name" : "societe", "NameSpace" : "historic" }, { "Datatype" : "str", "ID" : 12, "Name" : "testvar", "NameSpace" : "historic" }], "Total" : 2 }

 

 

Florian

 

PROXIMITÉ CLIENT

OBSERVER - ANALYSER  - COMPRENDRE

POUR AGIR EN FIDELISATION ET RENTABILITE

Tél : 02 23 30 03 26 . Fax : 02 23 30 01 80

Email :  <mailto:florian@proximite-client.fr> florian@proximite-client.fr

Web :  <http://www.proximite-client.fr/> proximite-client.fr

 

De : Arnaud BRETON [mailto:notifications@github.com] 
Envoyé : vendredi 20 février 2015 10:21
À : mailjet/mailjet-apiv3-php-simple
Cc : florianproxi
Objet : Re: [mailjet-apiv3-php-simple] Créer contact avec valeurs champs personnalisées (#57)

 

Je parlais d'un GET sur contactmetadata, pas d'un POST

**Comment by florianproxi** [comment]
{ "Count" : 2, "Data" : [{ "Datatype" : "str", "ID" : 11, "Name" : "societe", "NameSpace" : "historic" }, { "Datatype" : "str", "ID" : 12, "Name" : "testvar", "NameSpace" : "historic" }], "Total" : 2 }

**Comment by fturk** [comment]
J'ai trouver car ta proprièté est en historic mais la en static ça va marcher

**Comment by florianproxi** [comment]
@fturk Merci c'était ca, pas très explicite comme erreur... Et puise static c'est pas censé bouger comme donnée...

**Comment by fturk** [comment]
Derien @florianproxi c'est vrai mais je pense que mailjet va bientôt nous fournir une doc assez explicite et complet :D

**Comment by arnaudbreton** [comment]
Merci @fturk pour avoir trouvé l'erreur!

Nous sommes en cours de re-fonte de notre documentation et j'ai bien pris note de ce manque d'explication sur cette propriété qui n'est effectivement pas des plus claires. Nous l'ajouterons au futur guide.

Si le problème est résolu, pouvez-vous fermer cette issue @florianproxi svp? Merci!
