### ISSUE TITLE
Newsletter send dont work

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#58]
https://api.mailjet.com/v3/REST/newsletter/108/Send
{
    "ErrorInfo": "",
    "ErrorMessage": "Action \"Send\" of Resource \"NewsLetter\" does not allow this method.",
    "StatusCode": 405

}

Je ne comprend pas ???

**Comment by arnaudbreton** [comment]
Send en tout minuscule ?

**Comment by fturk** [comment]
pareille

**Comment by arnaudbreton** [comment]
Quelle méthode HTTP tu utilises ?

**Comment by fturk** [comment]
http://dev.mailjet.com/email-api/v3/newsletter-send/

**Comment by arnaudbreton** [comment]
Mais fais-tu un POST ici ?

**Comment by fturk** [comment]
Oui mais j'ai résolu le problème. Le problème ne venais pas d'ici mais ailleur, désolé :D
