### ISSUE TITLE
Newsletter URL problem?

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#59]
Bonjour,

Lorsque j'envoie ma newsletter, l'API génére un URL qui permet de visualiser la newsletter envoyé via le web mais lorsque j'accède à cette URL ça ne m'affiche pas la newsletter que j'ai envoyé. 

Est-ce normal ?

**Comment by florianproxi** [comment]
@fturk Moi quand j'affiche la version en ligne via la balise [[PERMALINK]] j'obtiens par exemple cette url: http:///pgzs.mj.amnl/Yht/f.html?UNSUB_PARAMS 

Le lien est incorrect... Comment se fait ce ? Bonne question ^^

**Comment by fturk** [comment]
Oui j'ai exactement comme toi @florianproxi

**Comment by florianproxi** [comment]
Alors qu'en début de semaine dernière tout fonctionnait nikel !

**Comment by arnaudbreton** [comment]
Bonjour @fturk,

Désolé pour ce problème. Tu mentionnes une réponse de notre support là dessus ? Si c'est le cas, peut-on stp fermer cette issue ? 

Merci de ta patience. 
Arnaud.

**Comment by fturk** [comment]
En faite l'issue #20 parle du [[PERMALINK]] pour la version en ligne mais moi dans cette issue #59 je parle du paramètre URL renvoyé par l'API lorsque j'envoie ma newsletter.

**Comment by arnaudbreton** [comment]
Merci, je suis d'accord que cela représente deux problèmes différents et je te remercie d'avoir fait attention à les séparer. Néanmoins, pour garder un seul canal de résolution de ce problème, je préférerai  continuer la discussion via notre support. 

Vu que le problème est identifié, nous mettrons à jour cette issue lorsqu'il sera résolu, pour référence.

Merci de ta compréhension.

**Comment by fturk** [comment]
D'accord @arnaudbreton :D

**Comment by arnaudbreton** [comment]
Merci @fturk!
