### ISSUE TITLE
Affecter plusieurs listes à un envoi

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#61]
Bonjour,

Je souhaiterai affecter plusieurs listes d'envoi à un envoi de campagne, savez vous si c'est possible ?
Car la méthode de création de campagne demande un ID liste.

Merci de votre aide :)

**Comment by fturk** [comment]
Salut,

Non tu ne peux pas, la seule solution est de faire un foreach en changeant l'ID liste.

**Comment by florianproxi** [comment]
@arnaudbreton Une amélioration sur ce point est-elle prévue ? Je pense que c'est utile et que ca servirai à beaucoup.
Dans mon cas c'est pour envoyer à la liste des destinataire ainsi qu'à la liste des adresses "mouchards".

**Comment by arnaudbreton** [comment]
@florianproxi, merci de partager vos retours. 

Cette fonctionnalité n'est pas prévue pour un futur proche dans notre feuille de route, mais cela reste bien sûr quelque que nous comptons ajouter. Nous pensions réaliser ceci en permettant de créer une liste de contacts virtuelle construite à partir de plusieurs autres listes. Est-ce que cela répondrait à votre besoin ?

**Comment by florianproxi** [comment]
@arnaudbreton Oui cela répondrait entièrement à mes besoins ! C'est exactement ce qu'il me faut et j'imagine que cela servirait également à d'autres :+1:

**Comment by arnaudbreton** [comment]
Parfait! Pourriez-vous svp fermer cette issue ? Je mettrai à jour, pour référence lorsque cette feature sera en production. Merci !
