### ISSUE TITLE
Télécharger une liste de contact

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#62]
Autre problème que je rencontre : comment télécharger une liste de contacts via l'API ?

Merci !

**Comment by fturk** [comment]
tiens:
$params = array(
                        "method" => "GET",
                        "ListName" => urlencode("TEST 1"),
                        "Limit" => -1
                    );
                    $array = $mj->listrecipient($params)->Data;
                    foreach ($array as $value){
                        $params = array(
                            "method"    =>     "VIEW",
                            "ID"        =>     $value->ContactID
                        );
                        echo $mj->contact($params)->Data[0]->Email;
                    }

**Comment by fturk** [comment]
D'ailleur y'a un problème dans le paramètre "ListName".
Il faut mettre le nom de la liste en urlencode("TEST 1") car sinon ça ne marche pas il ne prend pas en compte les espaces.

**Comment by florianproxi** [comment]
@fturk Je m'arrache les cheveux pour créer un batchjob d'export (http://dev.mailjet.com/email-api/v3/batchjob/)

**Comment by fturk** [comment]
tu veut exporter ta liste de contact dans un fichier excel ??

**Comment by florianproxi** [comment]
@fturk Oui exporter liste de contact (email + propriétés persos) dans un fichier excel (csv ou xls ou xlsx).

**Comment by fturk** [comment]
tu as d'autre manière mais tu veux absolument avec le batchjob ? (je sais même pas si c'est possible, en fin je ne sais pas :D)

**Comment by florianproxi** [comment]
Oui obligé avec le batchjob sinon le timeout de php va me bouler, et puis en terme de rapidité c'est le mieux.

Voici où j'en suis :
$params = array(
                    'method'            =>  'POST',
                    'JobType'           =>  'Contacts export',
                    'RefId'             =>  72
);
$result = $mj->batchjob($params);
var_dump($result);
echo $mj->debug();

**Comment by fturk** [comment]
ça te renvoie quoi ?

**Comment by florianproxi** [comment]
Ca me renvoie ceci :
object(stdClass)[2]
  public 'Count' => int 1
  public 'Data' => 
    array (size=1)
      0 => 
        object(stdClass)[3]
          public 'AliveAt' => int 0
          public 'APIKeyID' => int 231723
          public 'Blocksize' => int 0
          public 'Count' => int 0
          public 'Current' => int 0
          public 'Errcount' => int 0
          public 'ErrTreshold' => int 0
          public 'ID' => int 727218
          public 'JobEnd' => int 0
          public 'JobStart' => int 0
          public 'JobType' => string 'Contacts export' (length=15)
          public 'Method' => string 'addforce' (length=8)
          public 'RefId' => int 72
          public 'RequestAt' => int 0
          public 'Status' => string 'Allocated' (length=9)
          public 'Throttle' => int 0
  public 'Total' => int 1

**Comment by fturk** [comment]
La je sais pas, j'ai jamais utilisé le batchjob :( désolé @arnaudbreton pourra t'aider

**Comment by florianproxi** [comment]
Pas de soucis. Et puis si tu inspectes ce qui se passe lors du téléchargement CSV depuis ton inteface mailjet tu verras que c'est un batchjob que c'est effectué, donc c'est faisable :)
Attendons l'aide de @arnaudbreton :)

**Comment by florianproxi** [comment]
@arnaudbreton je me permet de te relancer concernant cette issue :)

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi,

Désolé du retour tardif. J'ai la solution avec curl pour les calls API (cf. ci-dessous). Comme cela implique notre DATA API, je pense qu'il y a une modification du wrapper à prévoir. 

Je reviens vers vous au plus vite.
N'hésitez pas à ouvrir une PR si vous adaptez le wrapper pour ce cas entre temps.

En attendant, voici les calls à réaliser (pensez à remplacer les parties variables, :job_id, :list_id):
```bash
# Create the batchjob ressource
curl -X POST --user "MJ_API_KEY:MJ_API_SECRET" https://api.mailjet.com/v3/REST/batchjob/ -H 'Content-Type: application/json' -d '{
"JobType":"Contacts export",
"RefId": :list_id,
"Method": "addforce",
"Status": "allocated"
}'

# Create an ExportOptions file, via the DATA API
curl -X POST --user "MJ_API_KEY:MJ_API_SECRET" https://api.mailjet.com/v3/DATA/BatchJob/:job_id/ExportOptions/application:json -H 'Content-Type: application/json' -d '{
"Format": "csv",
"Locale": "en_US",
"FieldNames": "email", // Can add additional contact properties to export here
}'

# Run the BatchJob
curl -X PUT --user "MJ_API_KEY:MJ_API_SECRET" https://api.mailjet.com/v3/REST/batchjob/:job_id -H 'Content-Type: application/json' -d '{
"Status": "upload"
}'

# Check the BatchJob status
curl -X GET --user "MJ_API_KEY:MJ_API_SECRET" https://api.mailjet.com/v3/REST/batchjob/:job_id

# Get the export result, via the DATA API
curl -X GET --user "MJ_API_KEY:MJ_API_SECRET" https://api.mailjet.com/v3/DATA/BatchJob/730855/CSVData/text:csv
```

**Comment by florianproxi** [comment]
Merci @arnaudbreton pour votre réponse, cependant je suis pas du tout à l'aise avec le CURL. Donc sans wrapper comme pour l'utisation du REST c'est compliqué....

**Comment by florianproxi** [comment]
Rectification : j'ai réussi en modifiant la class mailjet !

**Comment by florianproxi** [comment]
Seul problème lors de la récupération du fichier via PHP.

**Comment by arnaudbreton** [comment]
@florianproxi Peux-tu nous en dire plus stp ? Merci!

**Comment by florianproxi** [comment]
Voici mon script pour générer et télécharger l'export CSV d'une liste :

<code>
//On crée le Batchjob
    $params = array(
                    'method'            =>  'POST',
                    'JobType'           =>  'Contacts export',
                    'RefId'             =>  $_GET['idListe'],
                    'Method'            =>  'addforce',
                    'Status'            =>  'allocated',
    );
    $result = $mj->batchjob($params);
    $IDjob = $result->Data[0]->ID;
    
    //On attribue les ressources du Batchjob
    $params = array(
                        'method'            =>  'POST',
                        'jobID'             =>  $IDjob,
                        'Format'            =>  'csv',
                        'Locale'            =>  'fr_FR',
                        'FieldNames'        =>  'email',
    );
    $result = $mj->BatchJob($params);
    
    //On lance le batchjob
    $params = array(
                        'method'            =>  'PUT',
                        'ID'                =>  $IDjob,
                        'Status'            =>  'upload',
    );
    $result = $mj->batchjob($params);

    //On check le status du batchjob
    $params = array(
                        'method'            =>  'VIEW',
                        'ID'                =>  $IDjob,
    );
    $result = $mj->batchjob($params);
    
    //On récupère le fichier
    $params = array(
                        'method'            =>  'GET',
                        'ID'                =>  $IDjob,
    );
    $result = $mj->BatchJob($params);
    var_dump($result);
    var_dump($mj->debug());
</code>

Et voici la partie rajoutée dans la class de l'API :
<code>
}else if($resource == "BatchJob"){
            if(isset($params['Format'])){
                $this->call_url = "https://api.mailjet.com/v3/DATA/BatchJob/".$params['jobID']."/ExportOptions/application:json";
            }else{
                $this->call_url = "https://api.mailjet.com/v3/DATA/BatchJob/".$params['ID']."/CSVData/text:csv";
            }
            
        }
</code>

Donc le soucis que j'ai maintenant c'est le téléchargement du CSV :)

**Comment by arnaudbreton** [comment]
Ok, cela me paraît être un bon départ ! 
Qu'est-ce qui pose problème pour le télécharger exactement ?

**Comment by florianproxi** [comment]
@arnaudbreton le soucis que j'ai c'est comment récupérer via PHP le résultat de l'export.

**Comment by arnaudbreton** [comment]
@florianproxi Je ne suis pas sûr de comprendre votre problème exact. Un appel curl en PHP permet de récupérer simplement le résultat: 

```php
<?

$curl_handle = curl_init();
curl_setopt($curl_handle, CURLOPT_URL, "https://api.mailjet.com/v3/DATA/BatchJob/:job_id/CSVData/text:csv");
curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl_handle, CURLOPT_SSL_VERIFYPEER, FALSE);
curl_setopt($curl_handle, CURLOPT_SSL_VERIFYHOST, 2);
curl_setopt($curl_handle, CURLOPT_USERPWD, 'MJ_API_KEY:MJ_API_SECRET');

$buffer = curl_exec($curl_handle);

var_dump($buffer);
```

**Comment by florianproxi** [comment]
@arnaudbreton Merci ca m'a permis de réussir à modifier le wrapper, tout fonctionne maintenant. Je peux clore cette issue.

**Comment by arnaudbreton** [comment]
Ravi de l'entendre @florianproxi. Cela serait super si tu pouvais ouvrir une PR avec ta version modifiée de ton wrapper. Penses-tu que c'est possible ? Merci d'avance !

**Comment by fturk** [comment]
Salut @arnaudbreton @florianproxi :D

J'ai une erreur à cette étape:
//On attribue les ressources du Batchjob
$params = array(
                    'method'            =>  'POST',
                    'jobID'             =>  $IDjob,
                    'Format'            =>  'csv',
                    'Locale'            =>  'fr_FR',
                    'FieldNames'        =>  'email',
);
$result = $mj->BatchJob($params);

**Comment by florianproxi** [comment]
@fturk c'est parce que j'ai modifé le wrapper. Comment je peux t'envoyer mon wrapper ?

**Comment by fturk** [comment]
tu as skype ?

**Comment by florianproxi** [comment]
@fturk Mail envoyé ;)

**Comment by arnaudbreton** [comment]
@florianproxi Le mieux serait de forker ce repo sur Github, appliquer vos modifications et soumettre une PR. Êtes-vous familier avec ce processus?

**Comment by fturk** [comment]
J'ai ajouté ça :

}else if($resource == "BatchJob"){ if(isset($params['Format'])){ $this->call_url = "https://api.mailjet.com/v3/DATA/BatchJob/".$params['jobID']."/ExportOptions/application:json"; }else{ $this->call_url = "https://api.mailjet.com/v3/DATA/BatchJob/".$params['ID']."/CSVData/text:csv"; }

    }

mais ça ne marche pas chez moi

**Comment by florianproxi** [comment]
@arnaudbreton Non je ne suis pas familier avec ce processus.

**Comment by arnaudbreton** [comment]
Ok, la première étape est de "forker" ce repo sur votre compte. A partir de là, cloner ce nouveau repo, appliquer les modifications dans une branche dédiée puis ouvrir la pull request: https://help.github.com/articles/creating-a-pull-request/

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi, as-tu réussi à forker ce repo pour pouvoir appliquer tes modifications ? Au plaisir de t'aider si besoin ! Merci

**Comment by arnaudbreton** [comment]
@florianproxi, as-tu eu l'occasion de pouvoir modifier le code afin d'ouvrir une PR? Merci !

**Comment by RiderFx3** [comment]
Bonjour @arnaudbreton , j'ai actuellement le même problème, je souhaite vérifier si un contact fait déjà partie d'une liste via son email, et ça me récupère les 10 premiers enregistrements de toute la liste.

J'en suis ici : 

`$mail = $this->_request->get('mail');
        $list_to_check = 1704204;
        // $mail = $this->_request->get('mail');

        $mj = new Mailjet();

        //On check si le contact existe dans la liste à checker
        $params = array(
            'method' => 'VIEW',
            'ListID' => $list_to_check,
            'Email' => $mail
            );
        $result = $mj->contact($params);
        var_dump( $result );`

Merci pour votre aide.

**Comment by eboisgon** [comment]
Bonjour @RiderFx3 

2 ressources de l'API peuvent vous etre utile ici : [/contact/$ID/getcontactslists](https://dev.mailjet.com/email-api/v3/contact-getcontactslists/) ou [listrecipients](https://dev.mailjet.com/email-api/v3/listrecipient/)

Avec Listrecipients vous pourrez faire cette appel : 

```
     $params = array(
        'ContactsList' => $list_to_check,
        'ContactEmail' => $mail
        );
    $result = $mj->listrecipients($params);
    var_dump( $result );`
```
Cela vous indiquera si le contact est inscrit dans la liste en vérifiant la présence ou non d'une réponse ou la propriété `IsUnsubscribed`

**Comment by RiderFx3** [comment]
Merci beaucoup pour ta réponse. 

Ce qui m'intéresse c'est donc listrecipient, j'avais un bug car il faut le mettre au singulier sans "s" à la fin.
J'arrive à récupérer le contact, avec son ID je devrais donc pouvoir le supprimer de l'autre liste. Je vais creuser ça, merci beaucoup.

**Comment by RiderFx3** [comment]
Bon du coup j'en suis là, et ça me retourne false alors que le contact existe bien et que j'ai bien récupéré son ID : 

`
$mj = new Mailjet();
        $params = array(
            'method' => 'POST',
            'Action' => 'remove',
            'ContactID' => $id,
            'ListID' => $list_to_delete
        );
        $result = $mj->listrecipient( $params );
        var_dump($result);
`

listrecipient ne marche pas dans le cas d'une suppression de liste ?

**Comment by eboisgon** [comment]
Bonjour RiderFx3, 

Pour continuer cette discussion de façon plus simple et plus pousse, pourriez vous ouvrir un ticket sur notre support  (https://app.mailjet.com/support/ticket/open)? 

Pourriez vous nous indiquez ici votre numero de ticket que nous puissions reprendre rapidement notre discussion. 

Merci d'avance

**Comment by RiderFx3** [comment]
Bonjour et merci encore pour votre réponse, voici le numéro du ticket : 740212
J'ai créé un nouveau sujet ici : https://github.com/mailjet/mailjet-apiv3-php-simple/issues/134
