### ISSUE TITLE
Nombre de contacts disponible dans un plan

### ISSUE THREAD

**Issue by dgrigy** [mailjet/mailjet-apiv3-php-simple#63]
Bonjour à tous,

Je viens de voir qu'il y avait une notion de "nombre de contact" dans un plan. Par exemple sur le Gold nous sommes limité à 100 000 contacts.
Est-ce que le fait de lancer un script qui supprime les vieilles listes de contact diminue le quota? ou alors une fois qu'un contact a été ajouté, même si il est supprimé par la suite, le quota reste le même?

Je vous remercie pour vos réponses!

**Comment by arnaudbreton** [comment]
Bonjour, 

Cette question n'étant pas directement liée à notre API et au wrapper PHP, je vous invite à joindre notre support via https://app.mailjet.com/support/ticket

Merci d'avance.
