### ISSUE TITLE
Créer groupe envoi renvoie NULL sur serveur web

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#64]
Bonjour,
Je viens de mettre mon développement en ligne sur un serveur web, j'ai un soucis avec la méthode de création d'une liste de contact, elle me renvoie NULL (la liste est bien ajoutée dans Mailjet pourtant...) alors qu'en local ca fonctionne très bien. 
Voici mon bout de code:
$params = array(
                        "method"    => "POST",
                        "Name"      => $_POST['libelle_groupe_bat']
        );
        $result = $this->mj->contactslist($params);

**Comment by florianproxi** [comment]
Même la méthode pour lister les listes de contacts me renvoie NULL alors qu'en localhost tout est ok.
Comprend pas...

**Comment by arnaudbreton** [comment]
@florianproxi Utilises-tu la version du repo ou celle modifiée pour #62 ?

**Comment by florianproxi** [comment]
Les deux me font la même erreur. En creusant un peu c'est cette ligne qui pose soucis :
$this->_response = json_decode($buffer, false, 512, JSON_BIGINT_AS_STRING);

Quand je la remplace par : $this->_response = json_decode($buffer, JSON_BIGINT_AS_STRING);
ca fonctionne.
Par contre j'obtiens un tableau associatif et non un tableau d'objets. 

Nota : je suis sur un serveur VPS OVH.

**Comment by arnaudbreton** [comment]
Quelle version de PHP utilises-tu ? 32/64 bits ? Merci

**Comment by florianproxi** [comment]
PHP : Version 5.3.3
OS : CentOS Linux 6.6

**Comment by florianproxi** [comment]
Je confirme c'est bien CentOS Linux 6.6 en 64 bits

**Comment by shubs** [comment]
Hello @florianproxi , 
Le wrapper *mailjet-apiv3-php-simple* requiert au minimum PHP 5.5.4. 
Il faut donc que tu fasses la mise à jour de ta version PHP.

**Comment by florianproxi** [comment]
Après la mise à jour de PHP de mon VPS OVH (fastidieux, merci OVH), tout roule.
Je clos cette issue.
