### ISSUE TITLE
Erreur quand je m'identifie sur le site de mailjet ?

### ISSUE THREAD

**Issue by fturk** [mailjet/mailjet-apiv3-php-simple#65]
Salut @arnaudbreton, j'ai remarqué aujourd'hui que je n'arrive plus à m'authentifier sur le site de mailjet. J'ai bien essayé de vider mon caches, cookies..... et même avec d'autres navigateur.

**Comment by arnaudbreton** [comment]
Bonjour @fturk, 

Désolé de l'apprendre. Peux-tu stp contacter notre support via https://mailjet.com/support/ticket ? Github est réservé aux issues API / wrapper PHP (pour celui-ci). 

Nous revenons vers toi au plus vite là dessus,
Merci de ta patience et compréhension.
Arnaud.
