### ISSUE TITLE
Groupe blacklist generale

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#66]
Bonjour,

Est il possible d'avoir une liste "Blacklist générale" sur son compte mailjet ?
Par sécurité, pour exclure de tout envoi les emails s'y trouvant.

Merci,

**Comment by arnaudbreton** [comment]
@florianproxi, les issues du wrapper PHP sont réservés à ce dernier et aux questions APIs. Pour toutes autres questions relatives à Mailjet, merci de contacter notre support https://app.mailjet.com/support/ticket
