### ISSUE TITLE
Import csv via APi => Gérer les erreurs, ignorer les lignes avec erreurs

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#67]
Bonjour,
Savez vous comment faire lors de l'import d'un CSV via l'API ignorer même si des erreurs apparaissent ? Et comment télécharger le CSV des erreurs (comme ce qu'on peut faire via l'admin de Mailjet).

Merci

**Comment by gorgorbhey** [comment]
pour l'import CSV, utilises uploadCSVContactslistData de la dernière version de l'API
la doc de cette fonction n'est pas encore faite.
tu peux gérer les erreurs avec le _response_code de l'objet

**Comment by arnaudbreton** [comment]
Le `batchjob` génère un fichier CSV avec la même structure que le fichier original, enrichi d'une colonne `error` du format `###error_msg###error_field` où `error_msg` est le message d'erreur et `error_field` le champ en erreur.

Par exemple:
```csv
email,importcsv,error
api@mailjet.com,test4, ###Duplicated email###email
```

Ce fichier peut être récupéré via l'URL https://api.mailjet.com/v3/DATA/BatchJob/:job_id/CSVError/text:csv où `job_id` est l'identifiant du BatchJob original.

**Comment by florianproxi** [comment]
@arnaudbreton Super arnaud, ca fonctionne nikel. Je clos cette issue.
