### ISSUE TITLE
Problème personnalisation des campagnes emails

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#68]
Bonsoir

Problème lors de la personnalisation des campagnes.
J'ai toujours utilisé ce formatage pour l'affichage des paramètres contacts dans mes news : [[data:codeidbateaux : ""]]

Mais quand je m'envoie un test ca m'affiche ceci : " 

Comment se fait ce ?

**Comment by gorgorbhey** [comment]
[[data:CODEIDBATEAUX]] ça le fera

**Comment by florianproxi** [comment]
Salut @gorgorbhey 
Non ca fonctionne pas... Si je met [[data:codeidbateaux:"valeur"]] ca fonctionne, mais si je ne veux pas mettre de valeur par défaut ca ne fonctionne pas...

@arnaudbreton une idée du pourquoi ???

**Comment by gorgorbhey** [comment]
[[data:CODEIDBATEAUX]] ça marche chez moi
tu as quelle version de l'API ?

**Comment by florianproxi** [comment]
@gorgorbhey j'utilise l'API V3

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi,

Désolé pour le délai de réponse. La valeur par défaut est obligatoire. Pour obtenir une valeur vide, un espace suffit.

Voici un exemple fonctionnel: 
```php
<?
include_once('php-mailjet-v3-simple.class.php');
$mj = new Mailjet('MJ_API_KEY', 'MJ_API_SECRET');

$newsletter = $mj->newsletter(array(
	"method" => "POST",
	"Title"=>"Friday newsletter",
	"Locale"=>"en_US",
	"Subject"=>"My Friday newsletter",
	"HeaderLink"=>"www.example.com",
	"Sender"=>"Mailjet API",
	"SenderEmail"=>"api@mailjet.com",
	"ContactsListID"=>"1"
));

$ID = $newsletter->Data[0]->ID;

$mj->newsletterDetailContent(array(
	"ID" => $ID,
	"method" => "POST",
	"Html-part" => '<div>Hello world [[data:importcsv: ]]</div>'
));

$mj->newsletterSend(array(
	"ID" => $ID,
	"method" => "POST"
));
```

**Comment by arnaudbreton** [comment]
@florianproxi, votre problème est-il réglé avec la solution que j'ai posté ? Merci.

**Comment by florianproxi** [comment]
Et voilà ça ne fonctionne plus.... Ça fonctionnait bien jusqu'à présent....
Pourquoi vous changez sans arrêt les choses ?????

**Comment by arnaudbreton** [comment]
@florianproxi, pouvez-vous svp contacter notre support en incluant des détails sur votre problème ? Merci de votre compréhension.

**Comment by florianproxi** [comment]
@arnaudbreton J'ai déjà des tickets d'ouverts pour d'autres soucis depuis plus d'une semaine, toujours en attente de réponse "de la part de l'équipe technique" me répond on...

**Comment by florianproxi** [comment]
Je ne suis pas le seul, Kinder a routé une news avec vos services et a le même soucis : <PUB> [[data:firstname:""]], tentez de gagner une tablette Samsung et plein d’autres lots avec KIND

**Comment by arnaudbreton** [comment]
@florianproxi Le mieux serait de contacter notre support, avec de plus amples informations afin que nous puissions comprendre exactement ce qui ne va pas sur votre compte. 

Merci de votre compréhension.
