### ISSUE TITLE
Using the php-mailjet-v3-simple.class.php and example - Duplicate e-mails

### ISSUE THREAD

**Issue by jambrose00** [mailjet/mailjet-apiv3-php-simple#74]
I am finding using the php-mailjet-v3-simple.class.php file and the example for just sending an e-mail through the system that I am getting duplicate e-mails. On the mailjet dashbord, I am getting sent two e-mails as well.
Within the example, there is only 1 function call, so I am not sure what is going on.

**Comment by Gormador** [comment]
Hi @jambrose00 !

First of all, thank you for your interest in Mailjet!

We conducted some tests on our end trying to replicate your issue but didn't get any problem.

Could you paste here the incriminated portion of your code? Don't forget to delete your credentials (your mailjet API keys) from the file!

**Comment by jambrose00** [comment]
Many thanks for your quick response Gormador.

Basically, I am using the php-mailjet-v3-simple.class.php, along with the example code:


<?
include("php-mailjet-v3-simple.class.php");

function sendEmail() {
    $mj = new Mailjet();
    $params = array(
        "method" => "POST",
        "from" => "e-mail as per the e-mail setup in Mailjet",
        "to" => "my e-mail address",
        "subject" => "Hello World!",
        "text" => "Greetings from Mailjet."
    );

    $result = $mj->sendEmail($params);

    if ($mj->_response_code == 200)
       echo "success - email sent";
    else
       echo "error - ".$mj->_response_code;

    return $result;
}


sendEmail();
?>

**Comment by Gormador** [comment]
You're welcome :-)

There is absolutely no issue with the code, so this must be a problem with the API and not the wrapper seeing as we can't reproduce the issue with the exact same code as yours.

I invite you to contact Mailjet's support team through [here](https://app.mailjet.com/support/ticket).

**Comment by GuillaumeBadi** [comment]
### Hey @jambrose00 :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
