### ISSUE TITLE
Message ID issue

### ISSUE THREAD

**Issue by ariouche** [mailjet/mailjet-apiv3-php-simple#75]
Hello,
I've been using the php-mailjet-v3-simple.class.php class in order to interact with mailjet apiv3.
Each time I send an email using that method: $mj->sendEmail and I var_dump($Mailjet->_response), the message ID (Data[0]) always return an id with the same last 3 digits '336'.
Am I using the API correctly?

```
object(stdClass)#1116 (3) {
  ["Count"]=>
  int(1)
  ["Data"]=>
  array(1) {
    [0]=>
    object(stdClass)#1114 (1) {
      ["ID"]=>
      string(17) "13792285401457336"
    }
  }
  ["Total"]=>
  int(1)
}
```

**Comment by arnaudbreton** [comment]
Hi @ariouche,

First of all, thanks for your interest in Mailjet! 

For performance purposes, we're incrementing the message ID by 1,000 for every email sent explaining why several consecutive messages IDs will only differ on the 4th last digit. Nothing wrong here.

Please close the ticket if everything is OK for you. For further questions, feel free to open another issue.

Best,
Arnaud

**Comment by GuillaumeBadi** [comment]
### Hey @ariouche :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
