### ISSUE TITLE
Problems adding contacts

### ISSUE THREAD

**Issue by rplacom** [mailjet/mailjet-apiv3-php-simple#77]
Hi!

Regarding my last post asking Arnaud and replied by fturk, I created a new issue as Arnaud said.

Thank you for you fast reply, fturk. However, seems that it not worked for me, probably I'm doing something bad.

I've included your function on the php-mailjet-v3-simple.class.php and then I tried to call it, but nothing is showed on the page.

The code is so simple:

```
<?
include("php-mailjet-v3-simple.class.php");

$apiKey = 'xxxxxxx';
$apiSecret = "xxxxxx";

$mj = new Mailjet($apiKey, $apiSecret);
echo 'Contact ID: '.$mj->getIdContact_contact('test2@test.aaa');

?>

```

Do you see any error here? 

Thanks!

**Comment by fturk** [comment]
please check your mailjet class and give me getIdContact_contact() function

**Comment by rplacom** [comment]
Hi! 

The same code that you posted before :)

````

	public function getIdContact_contact($s_contactEmail){
		$params = array(
			"method" => "VIEW",
			"ID" => $s_contactEmail
		);
		return $this->contact($params)->Data[0]->ID;
	}

````

**Comment by arnaudbreton** [comment]
Thanks @rplacom for creating an new issue.

The @fturk solution is to retrieve an existing contact, which is not exactly what you want to achieve here if I understood correctly. 

Your solution looks correct and works perfectly on my side. Please also note that when a Contact already exists, the API will return a `400` status code for this error.

```php
$mj = new Mailjet($apiKey, $apiSecret);

$Cemail = 'test3@test.aaa';
$params = array(
    "method" => "POST",
    "Email" => $Cemail
);

$result = $mj->contact($params);

echo 'var dump:'.var_dump($result).'<br>';
echo 'ID:'.$result->Data[0]->ID.'<br>';
echo '<hr>';

if ($mj->_response_code == 201)
   echo "success - created contact ".$Cemail;
else
   echo "error - ".$mj->_response_code;
```

```php
php issue_77.php
object(stdClass)#2 (3) {
  ["Count"]=>
  int(1)
  ["Data"]=>
  array(1) {
    [0]=>
    object(stdClass)#3 (11) {
      ["CreatedAt"]=>
      string(20) "2015-04-27T15:28:15Z"
      ["DeliveredCount"]=>
      int(0)
      ["Email"]=>
      string(15) "test3@test.aaa3"
      ["ID"]=>
      int(295)
      ["IsOptInPending"]=>
      bool(false)
      ["IsSpamComplaining"]=>
      bool(false)
      ["LastActivityAt"]=>
      string(0) ""
      ["LastUpdateAt"]=>
      string(0) ""
      ["Name"]=>
      string(0) ""
      ["UnsubscribedAt"]=>
      string(0) ""
      ["UnsubscribedBy"]=>
      string(0) ""
    }
  }
  ["Total"]=>
  int(1)
}
var dump:<br>ID:295<br><hr>success - created contact test3@test.aaa3
```

**Comment by rplacom** [comment]
Hi Arnaud,

Yes, if I try to run the code twice I get the error code 400, as you said.

But it was not the problem, I guess. The contact is created, but there isn't nothing on the $result variable. 

I tried with other mailjet account (changing the api key and secret) with the same result, I don't understand. Also I tried on other server with different PHP version, and the same.

Well, my goal not is to get the contact ID, this was just a test. Actually I want to take N contacts of my database, put them on a mailjet contact list, select a template, and then create / send the campaign. I did it with the mailjet previous API version and worked fine, but it was not REST i guess. 

Maybe there is a better / quicky solution for implement my idea, what's you opinion?


Thank you again!

**Comment by arnaudbreton** [comment]
Hi @rplacom,

Sorry to hear this. Could you please share with us your PHP version and confirm you're using the [last public release](https://github.com/mailjet/mailjet-apiv3-php-simple/releases/tag/1.0.6) of our PHP Wrapper?

To upload many contacts, we gonna release new API endpoints to address this more easily in the coming weeks. I'll obviously let you know as soon as it's released. For the time being, you can import a CSV and associate contacts to list(s) afterwards. Is it something that could work for you? 

Templating is not something you can achieve via our public API at the moment. Here again, we're in the process to release new API endpoints in the coming months for this purpose. Meanwhile, I invite you to read our [newsletter guide](http://dev.mailjet.com/guides/newsletter-guide/) to learn how-to upload your the HTML / Text content (detailcontent action) and send / schedule your campaign.

Hope this helps.
Arnaud.

**Comment by rplacom** [comment]
Hi!

The CSV import can be really helpful, I'll check it.

My PHP version is 5.3 and yes, I'm using the latest version of your PHP Wrapper.

However, I need to select the HTML for the campaign, so maybe I should be waiting for the new functions on the public API. 

Thank you again for your help, I'll check the future API releases.


Ramon
