### ISSUE TITLE
Send email - Error 400

### ISSUE THREAD

**Issue by Jonathan2104** [mailjet/mailjet-apiv3-php-simple#78]
Bonjour,

J'ai mis en place tous les composants pour le fonctionnement de cette API, j'ai copié/collé le code pour envoyer un simple email "sendEmail()", et j'ai toujours en retour une erreur 400.

Une idée du pourquoi? (je suis sur un compte mailjet gratuit)

Merci d'avance.

**Comment by arnaudbreton** [comment]
Bonjour @Jonathan2104,

Nous réservons cet espace à la résolution de problèmes avec le wrapper PHP et l'utilisation de l'API en général. Votre erreur semblant lié à un problème sur votre compte, pouvez-vous contacter directement notre support via https://app.mailjet.com/support/ticket ?

N'hésitez pas à inclure un extrait de votre code.

Merci de votre compréhension.

**Comment by GuillaumeBadi** [comment]
### Hey @Jonathan2104 :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
