### ISSUE TITLE
HTML body to a newsletter

### ISSUE THREAD

**Issue by Jysui** [mailjet/mailjet-apiv3-php-simple#8]
Hello, 

Have an example on using "Adding an HTML body to a newsletter", especially for the parameters available. (http://dev.mailjet.com/guides/newsletter-guide/)

Thank you in advance for your response 
kind regards

**Comment by dsampaolo** [comment]
Même problème ici, ce qui rend malheureusement l'utilisation de l'API (et donc de vos services) inutile en ce qui me concerne. Est-ce qu'on peut vous aider à quelque chose pour débloquer la situation ?

**Comment by arnaudbreton** [comment]
Bonjour,

Via une nouvelle version de l'API et de ce wrapper (pensez à mettre à jour votre code ou fichier composer), vous pouvez désormais utiliser l'action `send` ou `schedule` pour envoyer facilement vos newsletters.

Ces deux méthodes sont documentées dans notre guide dédié, disponible ici : https://dev.mailjet.com/guides/newsletter-guide/ 

Pour toutes questions ou problèmes liés à ces méthodes, n'hésitez pas à ouvrir une nouvelle issue.

**Comment by GuillaumeBadi** [comment]
### Hey @Jysui :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
