### ISSUE TITLE
Soucis avec la fonction sender() ?

### ISSUE THREAD

**Issue by raphaelPONS** [mailjet/mailjet-apiv3-php-simple#80]
Bonjour,

Je n'arrive pas à ajouter une adresse email d'envoi à un de mes sous comptes.

```
$params = array (
     "method" => "POST",
     "Email" => "sender@domain.com"
);

$mailjetSubAccount->sender($params);
```
Cela me retourne le message suivant : **"MJ19 Setting a value for property "Status" is not allowed"**,
alors que je n'ai pas défini le paramètre "Status".

Une idée d'où ça peut venir ?
Merci

**Comment by Gormador** [comment]
Bonjour @raphaelPONS ,

Tout d'abord, merci pour votre intérêt pour Mailjet !

Il semblerait que vous ayez résolu votre problème tout seul. Si c'est bien le cas, pourriez-vous indiquer ce qui était la cause de l'erreur afin que d'autres dans votre situation puissent trouver une solution sur cette page ?

Merci d'avance !

**Comment by GuillaumeBadi** [comment]
### Hey @raphaelPONS :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
