### ISSUE TITLE
Update contact 'isActive'

### ISSUE THREAD

**Issue by Colir** [mailjet/mailjet-apiv3-php-simple#83]
Bonjour,
je cherche désesperement à changer la valeur 'is Active' sur un contact sans success...
Voila l'appel que je fais.
```
$data = array(array('IsActive' => true));
$params = array(
        'ID' => "4665",
        'Data' => $data,
        'method' => 'PUT'
    );

echo json_encode($result);
```
Cela me retourne false et pour cause...la propriété 'Is Active' n'existe pas...

Voila le retour de l'api
```
Mailjet Object ( [
version] => v3 [secure] => 1 
[debug] => 0 
[apiKey] => ... 
[secretKey] =>...
[apiUrl] => https://api.mailjet.com/v3/REST 
[_method] => contactdata 
[_request] => PUT
[call_url] => https://api.mailjet.com/v3/REST/contactdata/4665 
[_request_post] => Array ( [Data] => Array ( [0] => Array ( [IsActive] => 1 ) ) )
 [_response_code] => 400 
[_response] => stdClass Object ( [ErrorInfo] => [ErrorMessage] => Invalid json input: object ".Data..item"->"TKeyValue" has no property "IsActive" [StatusCode] => 400 ) ) 
```
Comment modifier cette valeur 'is Active' ?
merci beaucoup.

**Comment by Gormador** [comment]
Bonjour @colir,

Tout d'abord, merci pour l'intérêt que vous portez à Mailjet!

Concernant votre problème, pourriez-vous copier / coller tout le code qui concerne votre utilisation de l'API ?

À première vue, il s'agit simplement d'un mauvais format de l'array data (voir le deuxième point de [cette partie du readme](https://github.com/mailjet/mailjet-apiv3-php-simple#contact-lists)).
L'array `$data` devrait être: `$data = array(array("Name"=>"IsActive", "Value"=>"True"));`

Mais pour être certain il me faudrait le code entier :-)

**Comment by Gormador** [comment]
Hum. Je pense être passé à côté de votre objectif.
Bien que ma réponse soit techniquement correcte, elle ne vous aidera peut-être pas dans votre cas.

Deux possibilités :
* Vous avez ajouté une propriété personnalisée nommée *IsActive* [ici](https://app.mailjet.com/contacts/lists/properties) et dans ce cas ma première réponse est la bonne.
* Vous souhaitez contrôler l'état de l'abonnement d'un contact à une liste de contacts. Dans ce cas, vous trouverez un example de code pour arriver à vos fins [ici](https://github.com/mailjet/mailjet-apiv3-php-simple#contact-lists) (cherchez `addContactToList` sur la page).

Cela vous permet-il de résoudre votre problème ?

**Comment by colir** [comment]
Bonjour,
en effet je pense que la seconde solution est la bonne : 
Je souhaite modifier l'etat de l'abonnement d'un contact à une liste de contacts.
Petite question supplémentaire, faut il utiliser l'id ou le contact id pour la fonction updateContact
```
function updateContactData($id) {
    $mj = new Mailjet();
    $data = array(array('Name' => 'lastname', 'Value' => 'Jet'), array('Name' => 'firstname', 'Value' => 'Mail'));
    $params = array(
        'ID' => $id,
        'Data' => $data,
        'method' => 'PUT'
    );
```
    merci

**Comment by Gormador** [comment]
[La documentation](http://dev.mailjet.com/email-api/v3/contactdata/), spécifie que `ID` et `ContactID` sont équivalents pour cette ressource.

Quoiqu'il en soit, et au cas où je n'aurais pas été suffisamment clair, ce n'est pas le code décrit dans la fonction `updateContactData` qu'il faut reprendre pour modifier l'état d'abonnement d'un contact à une liste de contacts, mais bien une adaptation de celui décrit dans la fonction `addContactToList`.

Cette fonction utilise la resource `listrecipient` ([doc ici](http://dev.mailjet.com/email-api/v3/listrecipient/)) qui possède deux propriétés pertinentes pour votre question : `IsActive` et `IsUnsubscribed`.
* `IsActive` est une propriété uniquement accessible par l'API (et pas par le site web) qui définit si le contact a été désinscrit d'une contactslist, sans que l'état (actif ou non) soit visible depuis le site web : à n'utiliser que dans des cas bien particuliers, donc. **La plupart du temps, il sera préférable d'assigner** `true` **à cette propriété lors de l'ajout d'un contact à une contactslist.**
* `IsUnsubscribed` définit si le contact a été désinscrit d'une liste de la même façon que le site web et est donc la manière à préférer pour contrôler l'état de l'inscription d'un contact à une contactslist (car reflété sur le site web).

Le code est donc :

    include("php-mailjet-v3-simple.class.php");
    $mj = Mailjet("api_key", "api_secret");
    
    // Filters array to get the listrecipient ID linking one contact to one contactslist
    $lrFilters = array(
         "Contact" => [CONTACT ID],
         "ContactsList" => [LIST ID]
     );

    $lr = $mj->listrecipient($lrFilters);
   
    // Parameters array to perform the update on the contacts subscription
    $params = array(
        "method" => "PUT",
        "ID" => $lr->Data[0]->ID,
        "ContactID" => [CONTACT ID],
        "ListID" => [LIST ID],
        "IsUnsubscribed" => "True"
    );

    $result = $mj->listrecipient($params);

    if ($mj->_response_code == 201)
       echo "success - contact ".$contactID." unsubed from the list ".$listID;
    else
       echo "error - ".$mj->_response_code;

Cela répond-il à vos questions ?

**Comment by Colir** [comment]
Merci beaucoup, je test cela et reviens vers toi.

**Comment by Colir** [comment]
J'ai essayer mais sans succes...
Voila le contexte :+1: j'ai plusieur inscrits à une liste qui on le statut "isActive" à false

``` 
$params = array(
	'limit' => -1,
	'status' => 'unactive',
    'ListName' => 'The%20Organic%20Newsletter%20FR'
);
$result = $mj->listrecipient($params); 
```
me retourne (extrait): 
``` 
{"ContactID":4667,"ID":4808,"IsActive":false,"IsUnsubscribed":false,"ListID":3,"ListName":"The Organic Newsletter FR","UnsubscribedAt":""}
``` 

J'aimerai donc les passer en 'isActive' : true
J'ai essayer avec cette fonction, sans succes....
``` 
$params = array(
    "method" => "PUT",
    "ID" => '4667',
    "ContactID" => '4808',
    "ListID" => '3',
    "IsActive" => "True"
);

$result = $mj->listrecipient($params);

if ($mj->_response_code == 201)
   echo "success - contact ".$contactID." unsubed from the list ".$listID;
else
   echo "error - ".$mj->_response_code;
   
echo json_encode($result);
``` 

Pouvez-vous me guider ?
merci

**Comment by Gormador** [comment]
Je vois que, dans le tableau de paramètres du dernier segment, vous avez inversé les valeurs associées à `ID` et `ContactID` par rapport au json retourné par la requête précédente.
Il se pourrait que cela soit votre problème. 

En revanche, il serait préférable que vous incorporiez le contenu de la variable `result` dans votre réponse afin que j'ai toutes les cartes en main pour vous répondre ;-)

**Comment by Colir** [comment]
result me retourne
error - 304false

**Comment by Gormador** [comment]
Même en inversant les deux ID ?

**Comment by Colir** [comment]
Cela me renvoye
```
error - 200{"Count":1,"Data":[{"ContactID":4667,"ID":4808,"IsActive":true,"IsUnsubscribed":false,"ListID":3,"ListName":"The Organic Newsletter FR","UnsubscribedAt":""}],"Total":1}
```
en refaisant un
```
$params = array(
    'limit' => -1,
    'status' => 'unactive',
    'ListName' => 'The%20Organic%20Newsletter%20FR'
);
$result = $mj->listrecipient($params); 
```
j'ai toujours
```
"Count":424,"Data":[{"ContactID":4668,"ID":4809,"IsActive":false,"IsUnsubscribed":false,"ListID":3,"ListName":"The Organic Newsletter FR","UnsubscribedAt":""}
```

**Comment by Gormador** [comment]
Bonjour @Colir 

Le plus simple serais que vous passiez l'état de tous les `listrecipients` à `"IsActive" = true`, et qu'en suite vous utilisiez `IsUnsubscribed` pour contrôler l'état de l'abonnement de vos contacts.

Ci-dessous, le code effectuant cette manipulation:

    $mj = new Mailjet(MJ_APIKEY_PUBLIC, MJ_APIKEY_PRIVATE);

    $lrs = $mj->listrecipient();

    if ($mj->_response_code == 200)
       echo "success\n";
    else
       echo "error - ".$mj->_response_code."\n";

    for ($i=0; $i<$lrs->Count; $i++)
    {
    	$lrID = $lrs->Data[$i]->ID;

    	$params = [
    		"method" =>	"PUT",
    		"ID"	=> $lrID,
    		"IsActive"	=> true
    	];

    	$mj->listrecipient($params);

    	if ($mj->_response_code == 200)
	       echo "success\n";
	    else
	       echo "error - ".$mj->_response_code."\n";
    }

**Comment by Colir** [comment]
Merci beaucoup pour votre aide.
Voila ce que j'ai fait

```
$recipParams = array(
    'limit' => -1,
    'status' => 'unactive',
    'ListName' => 'The%20Organic%20Newsletter%20FR'
);
$lrs = $mj->listrecipient($Params);

if ($mj->_response_code == 200)
   echo "success\n";
else
   echo "error - ".$mj->_response_code."\n";

for ($i=0; $i<$lrs->Count; $i++)
{
    $lrID = $lrs->Data[$i]->ID;

    $params = array(
        "method" => "PUT",
        "ID"    => $lrID,
        "IsActive"  => true
    );

    $mj->listrecipient($params);

    if ($mj->_response_code == 200)
       echo "success\n";
    else
       echo "error - ".$mj->_response_code."\n";
}
```

j'imagine que le resultat n'est pas immédiat ?

car en refaisant 
```
$params = array(
    'limit' => -1,
    'status' => 'unactive',
    'ListName' => 'The%20Organic%20Newsletter%20FR'
);
$result = $mj->listrecipient($params); 
echo json_encode($result);
```

ma liste de contact unactive n'a pas changé...

**Comment by Gormador** [comment]
Il s'agit d'une erreur dans mon code. Seuls les 10 premiers `listrecipient` sont affectés pour le moment... Ce qui n'est pas très pratique !

Je corrige le code de suite et reviens vers vous rapidement.

**Comment by Gormador** [comment]
@Colir : C'est bon, ce code-ci devrait fonctionner.

    
    $mj = new Mailjet(MJ_APIKEY_PUBLIC, MJ_APIKEY_PRIVATE);

    $limit = 100;
    $offset = 0;

    $count = 0;

    $lrData = [];

    do
    {
    	$getParams = [
    		"Limit"	=> $limit,
    		"Offset" => $offset
    	];

    	$lrs = $mj->listrecipient($getParams);

    	$lrData["Data"][] = $lrs->Data;

    	$offset += 100;
    	$count += $lrs->Count;

    }while ($lrs->Count != 0);

    $nbIt = count($lrData["Data"]);

	for ($j=0; $j < $nbIt; $j++)
	{
	    for ($i=0; $i<count($lrData["Data"][$j]); $i++)
	    {
	    	$lrID = $lrData["Data"][$j][$i]->ID;

	    	$params = [
	    		"method" =>	"PUT",
	    		"ID"	=> $lrID,
	    		"IsActive"	=> true
	    	];

	    	$mj->listrecipient($params);

	    	if ($mj->_response_code == 200)
		       echo "success".$j.":".$i."\n";
		    else
		       echo "error - ".$mj->_response_code."\n";
	    }
	}

**Comment by Colir** [comment]
J'ai du modifier la déclaration des array, car j'avais une erreur php (example)
```
 $params = [
            "method" => "PUT",
            "ID"    => $lrID,
            "IsActive"  => true
        ];
```
en 
```
 $params = array(
            "method" => "PUT",
            "ID"    => $lrID,
            "IsActive"  => true
        );
```

a l'execution, cela tourne en boucle sans fin....
merci pour votre aide.

**Comment by Gormador** [comment]
Ah oui, au temps pour moi, cette syntaxe pour les arrays a été intégrée en 5.4.

À part ça, donc, c'est ok ?

**Comment by Colir** [comment]
...ça tourne indéfiniment....mais apres l'avoir laissé quelques minutes, lorsque je reexecute
```
$params = array(
    'limit' => -1,
    'status' => 'unactive',
    'ListName' => 'The%20Organic%20Newsletter%20FR'
);
$result = $mj->listrecipient($params); 
echo json_encode($result);
```
ma liste est vide, donc a priori c'est bon.
Merci beaucoup pour votre aide !

**Comment by Gormador** [comment]
Ok.  
Il est sûrement normal que le traitement prenne du temps vu que le code que je vous ai fourni exécute un appel à l'API pour chaque `listrecipient` du compte. Or il existe une ressource `listrecipient` pour chaque association entre *un* `contact` et *une* `contactslist`. Donc potentiellement un *gros* volume suivant le nombre de ces associations sur votre compte.

Quoi qu'il en soit, si votre problème est résolu, n'hésitez pas à fermer cette issue ;-)

**Comment by GuillaumeBadi** [comment]
### Hey @Colir :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
