### ISSUE TITLE
Method CONTACT retrieve unknown contacts.

### ISSUE THREAD

**Issue by soberanes** [mailjet/mailjet-apiv3-php-simple#85]
Hi, I'm trying to get a contact by email, but when I use the method contact, as the docuementation says, I get test contacts but I can't get the contact I'm looking for, so I can't add it to a contact list.

This is my function to get contact by email.

<?php
function getContactByEmail($contactEmail) {
        $mj = new Mailjet();
        $params = array(
            "method" => "VIEW",
            "ID" => $contactEmail
        );
        return $mj->contact($params);
    }
?>

How can I get the contact by email?

**Comment by Gormador** [comment]
Hi @soberanes ,

First of all, thank you for your interest in Mailjet!

In order to get a contact from its email, you need to change the `ID` field name to `unique`, as specified in the *Note* just above [this section](https://github.com/mailjet/mailjet-apiv3-php-simple#newsletters) of the readme.

**Comment by soberanes** [comment]
Hi @Gormador , 
thanks for your reply, I did what you say but still I getting the same response, tests contacts.

This is what the function is giving me:

success - got contact paulsoberanes@gmail.com
object(stdClass)#3 (3) {
  ["Count"]=>
  int(10)
  ["Data"]=>
  array(10) {
    [0]=>
    object(stdClass)#4 (11) {
      ["CreatedAt"]=>
      string(20) "2014-10-13T16:47:19Z"
      ["DeliveredCount"]=>
      int(0)
      ["Email"]=>
      string(15) "eroslol@try.com"
      ["ID"]=>
      int(1)
      ["IsOptInPending"]=>
      bool(false)
      ["IsSpamComplaining"]=>
      bool(false)
      ["LastActivityAt"]=>
      string(20) "2014-10-13T16:47:19Z"
      ["LastUpdateAt"]=>
      string(0) ""
      ["Name"]=>
      string(0) ""
      ["UnsubscribedAt"]=>
      string(0) ""
      ["UnsubscribedBy"]=>
      string(0) ""
    }
...

But I'm not getting the contact with the email paulsoberanes@gmail.com

What I'm doing wrong?

**Comment by Gormador** [comment]
Could you insert this line just after `$mj = new Mailjet();` : `$mj->debug = 2;`

And send the output (an html formatted page) at api@mailjet.com?

Thanks in advance ;-)
We will get back to you on that.

**Comment by Gormador** [comment]
Hi @soberanes ,
Have you had the chance to

**Comment by soberanes** [comment]
hi @Gormador I didn't see this message.
I don't understand what do you want to say with "an html formatted page", I'm doing the subscription with AJAX, so I printed the result (including the line $mj->debug = 2;) in console, I got a JSON with 10 contacts, tests all of them.
Let me deactivate the AJAX request and try again.

**Comment by Gormador** [comment]
Sorry @soberanes , I wasn't clear: the html formatted page is what the integrated "debugger" outputs. This "debugger" is fully active when you put `$mj->debug = 2;` just after the `$mj = new Mailjet();` in your code.

The output looks like this:
![Example output](http://puu.sh/i89t5/b8d7432134.png)

**Comment by soberanes** [comment]
Hi @Gormador sorry, we suspended the project but now we have resumed.

I'm trying to save the name of a contact, updating the contact and adding it to the list.
But when I try to get the contact to know if it exists I get a list of contacts I don't know why.

```php
$exists = $mj->contact(array("method" => "VIEW", "unique" => $Cemail));`
```

This is what I get in debug mode as you say:

![mailjet_1](https://cloud.githubusercontent.com/assets/1027761/8560476/b765f180-24dd-11e5-8ef8-6b0c257954e8.png)

![mailjet_2](https://cloud.githubusercontent.com/assets/1027761/8560477/b7689f5c-24dd-11e5-873f-284fd7cae939.png)

Can you help me with this, please?
Thanks.

**Comment by Gormador** [comment]
Hi @soberanes,

Could you provide me with the version of the wrapper you are using? I don't get the same call url with the exact same call.
If you are using composer – if you don't, you really should, it's a great tool! ;-) –, be sure that you are using our latest release, `v1.0.7`. Preferably, don't clone directly from master.

**Comment by soberanes** [comment]
Hi @Gormador,
I reinstalled the wrapper with composer this time, I was working with an old version of the wrapper.

This time I had a 401 error whit the same method.

![401](https://cloud.githubusercontent.com/assets/1027761/8576141/b0639878-2565-11e5-85b8-5e1c0c4b750d.png)

**Comment by arnaudbreton** [comment]
Hi @soberanes, a 401 error means an authentification issue. Can you please confirm your [API credentials](https://app.mailjet.com/account/api_keys) are correct?

**Comment by soberanes** [comment]
@arnaudbreton your're right, it was an authentication error.
The method to get the contact works, but to update the contact data doesn't.

I'm getting 400 error, the message says Invalid key name: "name" but I already have a "name" property.

This is the error:
![400](https://cloud.githubusercontent.com/assets/1027761/8576753/ce171026-2569-11e5-8ce8-9b2fafad1600.png)

This is the properties section in Mailjet:
![propiedades](https://cloud.githubusercontent.com/assets/1027761/8576757/d97f5572-2569-11e5-809c-43615e53506d.png)

**Comment by arnaudbreton** [comment]
Hi @soberanes,

Here the error is caused by the type of your `contactmetadata` property, set to historic. 

Historic properties are designed to store all the occurrences and used later in segmentation aggregate operations, like `MIN`, `MAX`, `AVG`. 
If you want to store only a single property value to personalise your emails or segments contact lists, please use the `static` type.

Hope it helps,
Best.

**Comment by GuillaumeBadi** [comment]
### Hey @soberanes  :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
