### ISSUE TITLE
Limite récupération des statistiques (emails envoyés, ouverts, ...)

### ISSUE THREAD

**Issue by dgrigy** [mailjet/mailjet-apiv3-php-simple#86]
Bonjour à tous!

Je viens d'avoir un soucis avec la méthode messagesentstatistics(). Lors de mes tests à l’implémentation de l'API je récupérais bien, par exemple, tous les emails envoyés avec cet appel : 
$params = array(
					"method" => "GET",
					"AllMessages" => true,
					"CampaignID" => $campaignID
			);
			$reponse = $mailJetObject->messagesentstatistics ($params);

Je passe bien le paramètre AllMessages à true et pourtant que je ne récupère que 10 adresses.
Je sais qu'il y en a beaucoup plus car avec la méthode campaignstatistics la valeur de DeliveredCount est supérieur à 300....

$params = array(
				"method" => "GET",
				"ID" => $campaignID
		);
		$reponse = $mailJetObject->campaignstatistics ($params);

Quelqu'un aurait-il une idée?

Je vous remercie!

**Comment by Gormador** [comment]
Bonjour @dgrigy ,

La raison pour laquelle vous ne récupérez pas plus de 10 _messages_ par appel est que l'API limite par défaut le nombre de ressources retournées à 10.
(Documentation [ici](http://dev.mailjet.com/guides/filtering-resources-guide/))  
Pour outrepasser cette limite, deux solutions (une bonne, une mauvaise) :
* La mauvaise : mettre une limite assez haute pour récupérer toutes les ressources d'un coup.
  * Pourquoi mauvaise ? L'API impose une limite à 1000 et une limite trop grande augmente les risque de problèmes dus à une coupure de la liaison.
* La bonne : mettre une limite raisonnable (par exemple, 100) et ensuite utiliser un offset de 100 sur l'appel suivant pour récupérer les 100 ressources suivantes.

Exemple de code (sur une autre ressource mais le principe est strictement le même) :

    $mj = new Mailjet(MJ_APIKEY_PUBLIC,MJ_APIKEY_PRIVATE);

    $limit = 100;
    $offset = 0;
    $count = 0;
    $lrData = [];

    do
    {
    	$getParams = [
    		"Limit"	=> $limit,
    		"Offset" => $offset
    	];

    	$lrs = $mj->listrecipient($getParams);

    	$lrData["Data"][] = $lrs->Data;

    	$offset += 100;
    	$count += $lrs->Count;

    }while ($lrs->Count != 0);

**Comment by dgrigy** [comment]
Bonjour @Gormador 

Cela fonctionne nickel en effet. 
Je n'avais pas vu cette partie dans la documentation...

Merci!

**Comment by GuillaumeBadi** [comment]
### Hey @dgrigy :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
