### ISSUE TITLE
Outlook interprets as a spam

### ISSUE THREAD

**Issue by FantaSteex** [mailjet/mailjet-apiv3-php-simple#87]
Hi!

When I send an email through sendMail() method, Outlook does receive the email, but consider it as a spam.
It works for gmail adresses, but always gets in spam folder for Outlook.

I am using the following code : 

<?php

	include('src/Mailjet/php-mailjet-v3-simple.class.php'); //The include works, of course

        //Both keys were found on my MailJet account
	$apiKey = "XXXXXXXXXX"; 
	$secretKey = "XXXXXXXXXX";	

	$mj = new Mailjet($apiKey , $secretKey);
	$params = array(
             "method" => "POST",
             "from" => "sender@domain.com",
             "to" => "contact@domain.com",
             "subject" => "Sent by mailjet",
             "text" => "Trying to send through mailjet."
    );

    $mj->sendEmail($params);
    
    if ($mj->_response_code == 200)
          echo "In ya face Outlook!";
    else
          echo "Outlook won - ".$mj->_response_code;
?>

So, here is my question : Should I add others params? Like, maybe, "reply-to", or "return-path" if the class supports them, or am I stuck because of the Outlook configuration?

Thank you!

**Comment by Gormador** [comment]
Hi @FantaSteex ,

First of all, thank you for your interest in Mailjet!

Unfortunately, this doesn't seem at all related to the php wrapper itself but more to a deliverability issue.
Please submit a ticket to our support team [here](https://app.mailjet.com/support/ticket).

Have a good day!

**Comment by GuillaumeBadi** [comment]
### Hey @FantaSteex :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
