### ISSUE TITLE
Décalage de 2 heures programmation envoi

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#88]
Bonjour
J'ai un problème : quand je programme l'envoi, celui ci se réalise 2 heures plus tard (je vois cela en allant sur mon compte Mailjet).
Pourtant je suis bien sur le fuseau horaire de Paris... Une idée ?

Merci,

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi,

Peux-tu stp nous en dire plus sur comment tu programmes ta newsletter ? Merci !

**Comment by florianproxi** [comment]
$timestamp = strtotime($date);
        $annee = date('Y', $timestamp);
        $mois = date('m', $timestamp);
        $jour = date('d', $timestamp);
        $heure = date('H', $timestamp);
        $minutes = date('i', $timestamp);
        $date_for_mailjet = new DateTime($annee.'-'.$mois.'-'.$jour.'T'.$heure.':'.$minutes.':00.222Z');
        $date_for_mailjet = $date_for_mailjet->format('Y-m-d\TH:i:s.uP');
        
        $params = array(
                        "method"        =>  'POST',
                        "Date"          =>  $date_for_mailjet,
                        "ID"            =>  $_GET['idNewsletter'],
        );
        $dateEnvoiSQL = date('Y-m-d H:i:s');
        $result = $this->mj->newsletterSchedule($params);

**Comment by arnaudbreton** [comment]
Ce code génère une date sans timezone explicite, notre système l'interprète donc comme à une [date UTC](http://www.worldtimeserver.com/current_time_in_UTC.aspx), d'où le retard. Comme précisé dans notre [guide de gestion des newsletter](http://dev.local.mailjet.com/guides/newsletter-guide/#schedule), le format attendu ([ISO 8601](http://en.wikipedia.org/wiki/ISO_8601)) peut contenir le timezone. 

Dans ton cas, il faut remplacer le Z par "+02:00" pour préciser le fuseau horaire de Paris (UTC+02:00 en heure d'été,  UTC+01:00 en heure d'hiver).

**Comment by florianproxi** [comment]
@arnaudbreton en mettant +02:00 à la place du Z j'ai toujours un décalage de 2h...

![pbprogrammerenvoi](https://cloud.githubusercontent.com/assets/11058258/8038431/ceefa256-0e03-11e5-8f5a-05f7d1371d31.jpg)

**Comment by arnaudbreton** [comment]
Quel est le retour de l'API ?

**Comment by florianproxi** [comment]
@arnaudbreton Le retour API semble indiquer la bonne date de programmation de l'envoi.... Alors qu'en fait non ça repousse toujours à +2H (ici 20h28).

![retourapi](https://cloud.githubusercontent.com/assets/11058258/8039766/4156d0a0-0e0c-11e5-83ad-9262b31d834a.JPG)

**Comment by arnaudbreton** [comment]
Le retour API est donc correct mais pas l'affichage du côté du site web, c'est exact ?

**Comment by florianproxi** [comment]
C'est bien ca, le retour API est OK mais semble incorrect car la news ne s'envoie que 2h plus tard, en le vérifiant directement côté site web...

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi,

Problème identifié de notre côté. Je reviens vers vous lorsque celle-ci sera corrigée. En attendant, vous pouvez convertir la date utilisée en UTC avant d'appeler l4API pour contourner le bug de gestion des fuseaux horaires.

D'après mes tests, la fonction gmdate devrait vous permettre de le faire. Voici un exemple:
```php
date_default_timezone_set("Europe/Paris");
$date = "2015-06-16T11:30:00+02:00";
$timestamp = strtotime($date);
$annee = date('Y', $timestamp);
$mois = date('m', $timestamp);
$jour = date('d', $timestamp);
$heure = date('H', $timestamp);
$minutes = date('i', $timestamp);
$date_for_mailjet = new DateTime($annee.'-'.$mois.'-'.$jour.'T'.$heure.':'.$minutes.':00.222+02:00');
$date_for_mailjet = gmdate('Y-m-d\TH:i:s.uP', $date_for_mailjet->getTimestamp());
var_dump($date_for_mailjet);
```

Le retour est bien en UTC: `string(32) "2015-06-16T11:30:00.000000+00:00"`

Est-ce que cela fonctionne pour vous ?
Désolé pour la gêne occasionnée.

**Comment by florianproxi** [comment]
Je viens de tester, donc si je choisir un envoi pour 15h, l'API me renvoie la date du 2015-06-09T13:00:00Z
Mais quand je vais voir sur le site web de Mailjet la date et heure sont corrects...

**Comment by arnaudbreton** [comment]
@florianproxi, avec ce code l'API devrait te renvoyer l'heure que tu passes à l'API (la variable `$date_for_mailjet`) en UTC, donc oui, 15h heure française donne 13h UTC.

Si cela fonctionne pour toi, peux-tu stp fermer cette issue ? 

Le problème a été résolu de notre côté et la correction sera en production plus tard cette semaine. 
Je ne manquerai pas de te tenir informé lorsqu'elle le sera. 
Ce code n'a pas besoin d'être modifié suite à cette correction mais tu pourras le revoir pour repasser en fuseau de Paris si tu le souhaites.

Merci d'avance,
Arnaud.

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi, la correction de ce bug est désormais disponible. 

Comme discuté précédemment, le code donné ci-dessus n'a pas besoin d'être modifié suite à cette correction mais tu pourras le revoir pour repasser en fuseau de Paris si tu le souhaites.

Merci pour nous avoir remonté ce problème.
Arnaud.
