### ISSUE TITLE
[[Permalink]] ne garde pas les champs personnalisés

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#89]
Bonjour,

Je viens de m'apercevoir que lorsque l'on clique sur un lien de page miroir généré via [[PERMALINK]], les variables de personnalisation ne sont pas gardées...

Comment se fait il ?
Merci

**Comment by arnaudbreton** [comment]
@florianproxi merci de votre retour. 

Afin de pouvoir identifier plus en détails votre cas pouvez-vous svp contacter notre [support](https://app.mailjet.com/support/ticket) directement?

Merci de votre compréhension.
