### ISSUE TITLE
problème import emails incorrects

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#90]
Bonjour

J'ai importé un fichier csv qui contenait un email incorrect, celui ci l'a bien importé et du coup lors de l'envoi j'ai eu une erreur.
Cf capture ecran

![import mailjet](https://cloud.githubusercontent.com/assets/11058258/8063536/8e1821d6-0ed5-11e5-96bc-2d4b22a7d7f1.JPG)

**Comment by arnaudbreton** [comment]
@florianproxi, peux-tu stp contacter notre [support](https://app.mailjet.com/support/ticket), ce qui nous permettra de retrouver plus facilement le contexte de ton compte. Essaye au maximum du possible de fournir toutes les informations sur ton action (heure de l'import, ID du job dans l'API, etc.) afin que nous puissions rapidement identifier cela de notre côté.

Désolé pour la gêne occasionnée.
