### ISSUE TITLE
La programmation d'envoi ne fonctionne plus ?

### ISSUE THREAD

**Issue by TheExcalibur** [mailjet/mailjet-apiv3-php-simple#91]
Bonjour,

Voilà quelques temps (1 mois) que je n'avais pas eu besoin de l'API qui fonctionnait bien. Mais depuis aujourd'hui, sans toucher à mon code, les campagnes restent à l'état de brouillon sur l'interface.
La contactList s'upload bien, la newsletter (campagne) est bien crée, mais le schedule ne fonctionne plus.

Voici mon code :
$params = array(
  "method" => "POST",
  "ID" => $newsletter_id,
  "date" => date('Y-m-d').'T'.date('H:i:s+02:00')
  // "date" => "NOW"
);
$result = $mj->newsletterSchedule($params);

J'ai laissé le commentaire pour "date" => "NOW", parce qu'il y a un mois, cela fonctionnait aussi.

Auriez-vous une idée du pbm ?

PS : je viens de faire une mise à jour du wrapper pour m'assurer que le problème ne venait pas de là.

**Comment by florianproxi** [comment]
Salut @TheExcalibur  j'ai aussi rencontré le même soucis plus ou moins, jette un coup d'oeil à mon issue : https://github.com/mailjet/mailjet-apiv3-php-simple/issues/88

A+

**Comment by Gormador** [comment]
Bonjour @TheExcalibur ,

Tout d'abord, merci de ton intérêt pour Mailjet !

Afin que nous puissions te répondre plus facilement, pourrais-tu nous fournir la réponse de l'api avec ce call ?
Et, afin de savoir avec certitude si cette issue est liée à celle de @florianproxi , peux-tu nous confirmer que les mails ne sont pas envoyés plus tard que ce qu'ils devraient?

Merci d'avance !
