### ISSUE TITLE
list of php methods

### ISSUE THREAD

**Issue by wrossier** [mailjet/mailjet-apiv3-php-simple#94]
Hello,

where can i find a list of all php methods for this API ?
I read this doc : https://github.com/mailjet/mailjet-apiv3-php-simple
so i found this methods (for example) :
- $mj->myprofile();
- $mj->contact();
- $mj->contact($params);
...

But where can i find all available methods ?
Thanks,
Will

**Comment by Gormador** [comment]
Hi @wrossier,

First of all, thank you for using Mailjet!

Generally speaking, each resource listed on the [API's reference page](http://dev.mailjet.com/email-api/v3/apikey/) can be used as a method. Available parameters are listed in the "Properties" section of each resource.
So, for example, if you want to check out the available campaign statistics resources for your account, simply use `$mj->campaignstatistics()`.

For special API features, such as the Send API or the newsletter actions, they are documented in the README you already read.


I hope this helps!
Regards.
Gaëtan

**Comment by wrossier** [comment]
i found it, i just need to use this page : http://dev.mailjet.com/email-api/v3/apikey/
on the left sidebar i have all name's method, further according to my needs I pass parameters.

**Comment by wrossier** [comment]
Sorry @Gormador I was about to write, actually this is what I understood, but I thank you for your help =)
thank you a lot,
Will

**Comment by Gormador** [comment]
You are most welcome.

**Comment by GuillaumeBadi** [comment]
### Hey @wrossier :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
