### ISSUE TITLE
Parameter values must be urlencoded when building url in requestUrlBuilder

### ISSUE THREAD

**Issue by LouTerrailloune** [mailjet/mailjet-apiv3-php-simple#95]
We are currently unable to filter by email if the email contain a '+' sign for example.

**Comment by Gormador** [comment]
Hi @LouTerrailloune,

A fix has been introduced in the dev branch of the wrapper. It won't be release just yet, but if you want to see the change, it's [here](https://github.com/mailjet/mailjet-apiv3-php-simple/commit/ad50292).

Sorry for the delay in our response.

**Comment by arnaudbreton** [comment]
@LouTerrailloune could you please confirm it's working for you now? If so, please close the issue. Thanks!

We will notify you once we'll release the version including this fix.

Best,
Arnaud.
