### ISSUE TITLE
Exporter les bounces d'une campagne

### ISSUE THREAD

**Issue by florianproxi** [mailjet/mailjet-apiv3-php-simple#97]
Bonjour,

Je cherche à exporter les bounces d'une campagne mais impossible de trouver comment faire... Pouvez vous m'éclairer ?

Merci,

**Comment by Gormador** [comment]
Bonjour @florianproxi,

La ressource à utiliser est [bouncestatistics](http://dev.mailjet.com/email-api/v3/bouncestatistics/) avec comme paramètre `CampaignID`.

La réponse de l'API contient, pour chaque bounce l'`ID` du message concerné ainsi que le `ContactID` pour le bounce.

En espérant que cela vous aura aidé.

**Comment by arnaudbreton** [comment]
Bonjour @florianproxi, est-ce que cela a résolu votre problème ? Merci d'avance.
