### ISSUE TITLE
scheduleNewsletter with newsletter_id?

### ISSUE THREAD

**Issue by ibrahimmumcu** [mailjet/mailjet-apiv3-php-simple#98]
There is something that confused me.

I want to create a scheduled newsletter, but the example written by you wants newsletter_id parameter. Should I create a newsletter first, then schedule it?

I don't understand the example. Can anyone explain me how can I create scheduled newsletter?

**Comment by Gormador** [comment]
Hi @ibrahimmumcu,

First of all thank you for using Mailjet!

Regarding your issue, there is two things to understand:
 - Not everything is explained in the README of our different wrappers, so the whole Newsletter process isn't described in the README of this repo. For full documentation (not langage specific), see [here](http://dev.mailjet.com/).
 - You don't create a schedule**d** newsletter, but _**schedule**_ a newsletter. So yes, you need to create your newsletter first, then schedule it to send it.

For that second point, there is a guide over our main developers documentation [here](http://dev.mailjet.com/guides/newsletter-guide/) :-)

**Comment by ibrahimmumcu** [comment]
Oh, thank you so much @Gormador, everything is clear now :)

**Comment by GuillaumeBadi** [comment]
### Hey @ibrahimmumcu :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
