### ISSUE TITLE
IFRAME doesn't display 

### ISSUE THREAD

**Issue by bamboolix** [mailjet/mailjet-apiv3-php-simple#99]
Seems that the IFRAME's behaviour has changed. Using an API V3 token key I can no longer display the iframe. I get this display  :

![iframe](https://cloud.githubusercontent.com/assets/591755/8524121/7f6484ca-23f9-11e5-8eee-bd8ddc186bad.png)

the called URL is :  https://www.mailjet.com/campaigns?t=

in the URL I get a 404 error.

$params = array
		(				
				"method" => "POST",
				"AllowedAccess" => "campaigns,contacts,reports,stats,preferences,pricing,account",
				"APIKeyID" => $ApiKeyID,
				"lang" => "fr",
				"TokenType" => "iframe",
				"IsActive" => "true"
		);
		$result = $this -> m_oMailJet -> apitoken( $params );		
		$url = "https://www.mailjet.com/campaigns?t=".$result->Data[0]->Token;

**Comment by Gormador** [comment]
Hi @bamboolix ,

First of all, thank you for using Mailjet!

Coud you contact our support ([here](https://www.mailjet.com/support/ticket)) regarding this issue? This doesn't seem php-specific so they will be better suited to answer you.

Thanks in advance!

**Comment by bamboolix** [comment]
very well thanks for the Answer.

**Comment by GuillaumeBadi** [comment]
### Hey @bamboolix :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
